### ISSUE TITLE
[requirements] audiences

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#1]
From Kevin White @iadawn : 

I wonder about the 'People with stereotype and stigmatized perception of disability' target audience. It is quite a bit more negative than the other audiences, and wonder if it is a good one to focus on?

**Comment by haltersweb** [comment]
Maybe titling it differently such as "Breaking stereotypes and stigmatization"

**Comment by haltersweb** [comment]
People seeking a less stereotyped understanding of disability

**Comment by bakkenb** [comment]
I understand the comment from Kevin @iadawn about the audience type seeming more negative. However, in my opinion, we are not going to be creating negative content or videos that would deliver a "negative message" to and audience, but I believe that this in fact is an important audience to list. It is an audience that is more negative, but that is the exact audience we are partly trying to reach and change the perception of. We have to define the audience as it is, even if it is negative.

**Comment by iadawn** [comment]
Point taken @bakkenb. As a follow-on thought, and perhaps for later consideration, who might that audience be reached?

**Comment by nitedog** [comment]
The same way as the other audiences (see objectives section).
