### ISSUE TITLE
[Script 3: Voice Recognition] Why use after injury?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#10]
Sequence 4 has the user continuing to use voice control after the injury has healed. Not quite sure what this intends to communicate... if it is the idea that repitition of the injury could be avoided it might be a bit subtle and also a bit too much going on.

It may be better to just show a person with a wrist injury (or bandage) acoiding using a mouse and using the voice recognition.

**Comment by yatil** [comment]
I think it is meant to show that having an injury can lead people to discover accessibility features. If so, this should be made more clear. You could show the person doing something that occupies their hands (like baking vegan cake :-p). They then remember to use voice.

**Comment by bakkenb** [comment]
Yes, that was the intent. One needs to technology to overcome a temporary disability, but when the disability is no longer present, the technology is already so adapted into their lives that they keep using it because it make life easier or more convenient.

**Comment by nitedog** [comment]
From Susan:

>  Also switch the order of the visuals in scene four to the person using the computer by typing and then the scene turning into the same person with a cast now using voice recognition.

From James:

> This doesn't seem to create enough of an emotional response to me. Yes useful with the cast, but I think people would say that's great but I'm back to regular after I get out of this because they think voice control is slower... Maybe create empathy for users that don't have the choice and instead of the person in a cast using it before and after the cast, what about a person in a cast, using a mobile device, and then when they say repetitive stress, show a closeup of a person's hands on a keyboard and as you pull out to the bigger picture, the person turns over their hands, palms up and you see scars on their wrists and them wearing a microphone/headset.

**Comment by nitedog** [comment]
This has now been split out. The idea is to just show different situations that one could be in, where voice recognition would be useful. I hope it is clearer now.
