### ISSUE TITLE
[4: Text to Speech] Include TTS voice

### ISSUE THREAD

**Issue by yatil** [w3c/wai-showcase-examples#100]
I think it would be super cool to have – in this showcase only – the text-to-speech engine read the bit in the last scene.

**Comment by shawna-slh** [comment]
+1

**Comment by nitedog** [comment]
The start sequence is being read by a screen reader, and in between as well (to show what it means to be inaccessible) - do you still suggest to have the last sequence also be read aloud? Can we keep this to editor's/producer's discretion, depending on how this will best work? (this can probably be done in post-production anyway, too).

**Comment by yatil** [comment]
It’s totally to editor’s/producer’s discretion.

**Comment by nitedog** [comment]
The last sequence spoken by a screen reader will be recorded, and we will check which version works better during post-production. There is screen reader voice at the beginning for sure.
