### ISSUE TITLE
[4: Text to Speech] Vital for blind, important/useful for reading difficulties, handy for others

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#106]
[important - show stopping]

<blockquote>2: Sometimes, listening can be easier than reading. That’s where text to speech software can help. 3: It’s technology that many people with visual disabilities have been relying on for years. 4: But it’s also an essential tool for people with dyslexia and very useful for people with difficulty reading text. 5: As well as some people who just like to multi-task.</blockquote>

This is not getting the importance across – the emphasis is wrong. Starting out with "listening can be easier than reading" sets the wrong stage – that it's handy instead of vital.
(related issue: https://github.com/w3c/wai-showcase-examples/issues/41 )

I think it's important to get this clearly communicated:
- It's **_VITAL**_ for people who are blind.
- It's **_very useful**_ (not quite "essential", maybe important) for some people with dyslexia or other difficulties reading text.
- It's _handy_ for people who just like to multi-task.

**Comment by nitedog** [comment]
It says "_sometimes_ listening can be easier than reading". We wanted to start this video by showing how beneficial this feature is for nearly anyone, rather than focus on the requirement alone.

How about if we change the next sentence to "It's technology that many people with visual disabilities require to use the computer"? Does that strengthen the criticality?

**Comment by shawna-slh** [comment]
Yes, that strengthens the criticality for the second sentence.

You could also counter/play off of "sometimes", e.g., something along the lines of: Sometimes, listening can be easier than reading. ...Sometimes reading isn't possible and listening is required
-- that's awkward, but you get the idea.

Also note that I think the next sentence should be tweaked. I do not think it's "essential" for people with dyslexia, compared to people who are blind.
(minor: I also suggested a tersification of "for some people with dyslexia or other difficulties reading text." -but that's totally editor's discretion)

**Comment by nitedog** [comment]
Script has been revised to address this issue (throughout, especially the start and ending).
