### ISSUE TITLE
Start/title and ending screens

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#108]
From @slhenry 

> In EOWG telecon https://www.w3.org/2016/02/12-eo-minutes#item03 we discussed the point(s) in: https://github.com/w3c/wai-showcase-examples/issues/47 and there was support for the idea of some visual text at the ending &/or beginning ("Adina: Yes that is a great idea and can use a banner to start and end as bookends to the action and idea demonstration. ... to help them walk away with a sense of an actionable item." "Eric: State topic first in a catchy way and then add referenced URL to bring clarity and uniformity.") I'm not seeing this in the updated scripts.

**Comment by nitedog** [comment]
@slhenry - what needs to be in the start and end screens?

# START SCREEN:
- Title of video (eg. "video captions")
- Title of resource (eg. "impact and benefits of web accessibility")?
- W3C & WAI logos?
- Copyrights? Credits?

# END SCREEN:
- URL of resource (eg. "www.w3.org/WAI/examples")
- W3C & WAI logos?
- Copyrights? Credits?

**Comment by gheake-1** [comment]
Would email point of contact be appropriate on the END SCREEN to gather feedback or any questions.

**Comment by bakkenb** [comment]
For the title "Start" screen, I think it should be simple so that it can be fast. Title of video and title of resource and including any applicable logos (W3C or WAI).

For the end screen, I like what is listed... URL of resource, logos, credits, & copyright.

**Comment by AndrewArch** [comment]
+1 to Brent

**Comment by nitedog** [comment]
# START SCREEN:
- (small) title of resource (eg. "web accessibility perspectives")
- (big) title of specific video (eg. "video captions")

# END SCREEN:
- URL of resource (eg. "w3.org/WAI/perspectives")
- W3C & WAI logos
- Copyrights

Note: the resource page (eg. "w3.org/WAI/perspectives") will have text to supplement the videos, links to further resources, and contact & feedback email.

**Comment by yatil** [comment]
- I’d suggest to not have the title of the specific video in the video [edit:] so that we have more surprise effect when people are looking at the videos[/edit]. (We can decide that in production.)
- I’d also **strongly** suggest to have individual (short-ish) links for each video.

**Comment by nitedog** [comment]
Agreed to keep video title per [face-to-face resolutions](https://www.w3.org/2016/03/18-eo-minutes.html#ResolutionSummary)
