### ISSUE TITLE
catch phrase

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#109]
From @slhenry 

>  Related point: "Actually, it might be really neat to have a catch phrase that communicates that point (vital for some; beneficial/useful for all/others) that we use in most or all of the videos..." https://github.com/w3c/wai-showcase-examples/issues/41

**Comment by nitedog** [comment]
Do you mean something like "[video captions] are essential for people with disabilities and helps many more" being said at the end of each video?

**Comment by shawna-slh** [comment]
yup! except catchier :-)

"[video captions]: essential for people with disabilities; helpful for all!"

**Comment by nitedog** [comment]
Doesn't that get boring after the 2nd or 3rd video? How essential do you feel this is?

**Comment by shawna-slh** [comment]
I think it's essential that the videos communicate that message -- as I've said in other GitHub issues. I do not think it's essential that there's the exact same catch phrase at the end of every video.

I'm not sure about the "get boring". I don't know how many people will watch most of the videos in one sitting. Maybe they will just watch the one or two that people point them to? Maybe they will read the page in between videos?

Maybe the repetition would be really neat and help to tie the videos together, in addition to getting across this important point?! Maybe we have a couple or few variations on the catch phrase that we use for different videos? -- e.g., "[Video Captions]: essential for people with disabilities; helpful for all!"; "[Colors with Contrast]: handy for all; important for people with disabilities." So we make the point very clearly and have the tie-in between the videos without negative repetition?

Perhaps the production company has good perspective on these ideas?

**Comment by yatil** [comment]
+1 to @slhenry

**Comment by sharronrush** [comment]
+1 to @slhenry

**Comment by nitedog** [comment]
@slhenry - scripts have been revised to address this issue. Do these endings address the issue?

**Comment by yatil** [comment]
(really mild suggestion) I am OK with the contents of the phrases, but I wonder if they can be catchier. Unfortunately I don’t have concrete suggestions to help with this. Maybe something like this could work: “Captions: Essentials for people with hearing impairments, beneficial to everyone.“

**Comment by iadawn** [comment]
I think flagging who it is essential for may become self-limiting. Maybe something more generic such as:

> Captions: essential for some, beneficial for all

Or, something more aspirational/abstract

> Captions: making the web possible, making the web better

**Comment by yatil** [comment]
Thanks @iadawn, I think this could generally be the right direction.

**Comment by gheake-1** [comment]
+1 to @slhenry

**Comment by bakkenb** [comment]
+1 to simple ending like this on the videos... Good suggestion Kevin.

> Captions: essential for some, beneficial for all

**Comment by AndrewArch** [comment]
+1 to catch phrase, but keep it clear and simple and to the point

**Comment by susanatx** [comment]
@iadawn's abstract suggestion is my first choice.

If we were leaning in the direction of generic reference to user needs here are some other variations:

Critical for some
Helpful for all

Needed by some
Useful for all

**Comment by bakkenb** [comment]
Currently each script has a different "version" of this catch phrase. It is a bit longer than some of the examples set forth in this issue conversation. I am okay with the phrasing of the current narration of the catch phrase. They are in alignment and 'spirit' of this thread. Just wanted to check to see if others feel they really should be as short as some of the comments listed above.

**Comment by shawna-slh** [comment]
Maybe I'm not looking at the latest versions? It seems some don't have this at all (e.g., http://w3c.github.io/wai-showcase-examples/script4.html) and other ending narrations are not catchy and not meeting the point of this thread. They are too long and too different and too dull. "XYZ allows access for people with XYZ disabilities and many more." is wimpy and does not get across the points above.

I still think the endings should be short and more similar -- not exactly the same, but very similar and **with similar cadence**. Could be versions of this, depending on which words best fits the topic:

<blockquote>
XYZ: [essential/vital/critical/important/needed(by)] for some, [beneficial/useful/helpful/handy] for [all/everyone]
</blockquote>

(I agree with Kevin not to limit to specific disabilities.)

**Comment by bakkenb** [comment]
If we go with the short, snappy phrase, which I am leaning more towards every moment, I like the following that I pulled from Shawn's (@slhenry) last comment:

<b>XYZ: essential for some, beneficial for everyone</b>

**Comment by shawna-slh** [comment]
To clarify: I suggest that we use _different_ words from the brackets for some topics, as appropriate -- e.g., captions and text-to-speech are _essential_; however, I wouldn't say that Large Activation Areas is essential, just important.

I think having minor variety is good - as Shadi (@nitedog) mentions near the top of the thread, partially to avoid being too "boring" or redundant. As long as it is the same structure and cadence, I think it will provide the nice consistency.

**Comment by bakkenb** [comment]
+1 to @slhenry

**Comment by James-Green** [comment]
While i think having different words for each is fine, I feel we need to have a very consistent structure and the scripts aren't there yet...  I would suggest something short and memorable using one of the following structures: 
- **[topic]: [essential, or important, etc.] to some; [handy, or helpful, etc.] to everyone...** or 
- **[topic]: [essential, or important, etc.] to [disabled user group that benefits]; [handy, or helpful, etc.] to everyone...**

**Comment by susanatx** [comment]
+1 to @slhenry and +1 @James-Green  While I was reading through the scripts the "and many more" started to just feel like a shrug to me at the end. We definitely need more punch because we don't want any last impressions to be along the line of "eh, you know, accessible or something."

And I agree with James that a consistent structure - the less wordy the better - is key. Many of the ideas in this thread would work.

**Comment by yatil** [comment]
Here are some proposals based on @James-Green’s suggestions. More brainstormings, but at least something that we can talk about and see all the catch phrases in one spot, which I found helpful:
1. Captions: Essential for people with hearing impairments; useful for everyone.
2. High-Contrast Colors: Crucial for people with vision impairments; useful in for everyone in difficult light environments.
3. Supporting Voice Recognition: Indespensable for people with physical disabilities; helpful for everyone in certain situations.
4. Supporting Text to Speech: Essential for people with (some|a wide range of) disabilities; useful for everyone.
5. Clear Layout and Design: Allows access for people with disabilities; improves the user experience for everyone.
6. Understandable Notifications and Feedback: Essential for people with disabilities; helpful for everyone.
7. Large Activation Areas: Needed by people with disabilities; making websites and apps less frustrating to use for everyone. 
8. Customizable Text: Makes websites readable by people with (physical?) disabilities; improves readability for everyone.
9. Clear and Understandable Content: Crucial to provide access to people with learning and cognitive disabilities; easier to comprehend for everyone.
10. Keyboard Compatibility: Allows access for people with physical disabilities; useful for everyone.

Note: I think some of them are still a bit long, but that stems mainly from the “people with disabilities” phrase that we need to use. I tried to be quite specific with both, the disability where the topic applies to most and the areas where the topic helps everyone. Sometimes that worked out better, sometimes not. (But who said it would be easy, right?!)

**Comment by nitedog** [comment]
OK, it seems we are converging towards a common structure that most agree with. Great.

However, I'm struggling with the ending - is the use of "for everyone" or "all" too exaggerated? Are captions really useful for _everyone_?

**Comment by bakkenb** [comment]
Good question @nitedog. I don't have a critical need for captions, but I use them often for a few different reasons depending upon the circumstance.

Looking at the rest of the scripts, the only one that I have not used to this point is voice recognition. I think that is simply because I have not had a specific reason to experiment with that technology. I do believe that will become widely used in the near future though.

So, to me, these CAN all be really useful to everyone. IMHO I don't feel it is exaggerated.

**Comment by sharronrush** [comment]
yes

On Thu, Mar 10, 2016 at 3:21 PM, Shadi Abou-Zahra notifications@github.com
wrote:

> OK, it seems we are converging towards a common structure that most agree
> with. Great.
> 
> However, I'm struggling with the ending - is the use of "for everyone" or
> "all" too exaggerated? Are captions really useful for _everyone_?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/wai-showcase-examples/issues/109#issuecomment-195054839
> .

## 

Sharron Rush | Executive Director | Knowbility.org | @knowbility
_Equal access to technology for people with disabilities_

**Comment by nitedog** [comment]
OK, we now have the following phrases at the end of the videos:
- Video Captions: essential for some, useful for everyone.
- Colors with contrast: critical for some, useful for everyone.
- Voice recognition: essential for some, useful for everyone.
- Text to speech: essential for some, useful for everyone. (possibly read out by text to speech)
- Clear layout and design: important for some, beneficial for everyone.
- Notifications and feedback: important for some, beneficial for everyone.
- Large activation areas: critical for some, beneficial for everyone.
- Customizable text: critical for some, beneficial for everyone.
- Understandable content: important for some, beneficial for everyone.
- Keyboard compatibility: essential for some, beneficial for everyone.

**Comment by yatil** [comment]
Just having „for some“ feels too generic for me. – But I’m happy to go with it, if others feel so. At least it is brief and succinct.

**Comment by nitedog** [comment]
Yeah, I had that reaction too. But most cases it would need a long list and sometimes with more specific differentiation - for example, text to speech is essential for people with some types of visual disabilities and for people with some forms of cognitive and learning disabilities (combining this, like "for people with some types of visual, learning, and cognitive disabilities" is too ambiguous so we would end up with often long and confusing phrases).

**Comment by yatil** [comment]
Yeah, it gets complicated very quickly and we have the website which can go into slightly more detail.

**Comment by nitedog** [comment]
Working group resolution to use the consistent format:
-  **"(video subject) for an accessible web: essential for some, useful for all"**

https://www.w3.org/WAI/EO/wiki/EOWG_Meetings_2016#11_March_2016_Teleconference

**Comment by nitedog** [comment]
Resolution confirmed per [face-to-face resolutions](https://www.w3.org/2016/03/18-eo-minutes.html#ResolutionSummary)
