### ISSUE TITLE
[Script 3: Voice Recognition] Hearing the commands?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#11]
Just thinking about these videos, for some aspects hearing the commands the user in the video may be an important part to help viewers understand the narrative. Won't the voice over get in the way of that?

**Comment by bakkenb** [comment]
Yes, that is a good point. Especially for Sequence #5 it would be important to the video to allow the actors voice command of "submit" to be heard for clarity.

**Comment by nitedog** [comment]
Added a scene where we see/hear the person actually issue voice commands to operate the computer.
