### ISSUE TITLE
[Script 2: Color Contrast] title

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#111]
From @slhenry 

> I still suggest changing the title to "(Color) Contrast Ratio" per https://github.com/w3c/wai-showcase-examples/pull/64/files to lessen the chance that someone messes and up puts "color contrast" somewhere, e.g., in the video title or description or accompanying web pages.
> 
> Also a one-word pull request in GitHub that I assume was just an oversight but is minor and for TF discretion.

**Comment by nitedog** [comment]
There is a conflict with this pull request, so not able to merge it... :/

Actually we _do_ want to use these titles, so we need to decide on them. I think "(Color) Contrast Ratio" is really quite jargony and not easy to understand for most of our target audience.

**Comment by shawna-slh** [comment]
brainstorms:
Colors with Contrast       <-- pro: puts "colors" first. I think kinda catchy :-)
Contrast between Colors
...

**Comment by nitedog** [comment]
Contrast of Colors
(I like "Colors with Contrast", though)

**Comment by nitedog** [comment]
Went with "colors with contrast" - also in the ending of the film.
