### ISSUE TITLE
[Script 5: Layout and Design] too much going on

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#113]
From @yatil 

> I still think there is a lot going on, but I guess that is my lack of imagination ;-). Go ahead!

**Comment by nitedog** [comment]
Please explain - what is too much? What would you want to have removed?

**Comment by yatil** [comment]
For example four seconds for the sequence

> Show someone in a kitchen – they’re trying to make a cup of coffee but the kettle is in a cupboard, the coffee is the other side of the room and the mugs are somewhere else entirely.

seems incredibly detailed to put into that small amount of time. That said, it is surely do-able, and I trust that the production and you will make it work. I basically wanted to say that I’m happy that I don’t have to do the work to make this fit :-)

**Comment by nitedog** [comment]
Maybe it will be tight but the intent is to have quick cuts. The focus is on the person not finding the things rather than on making the coffee itself. Maybe standing in front of the kitchen, looking for things, and scratching or shaking the head from despair. I think ~4 seconds should be enough to show that. But you are right, let's leave this up to the producers... ;)
