### ISSUE TITLE
[Script 7: Large Activation Areas] jargony

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#119]
"activation area" is very jargony, not lay-person language. I think previous iteration had "click areas". Was that changed because it also includes areas to tap for touch screens -- or other reasons?

Maybe we can use both terms interchangeably?

**Comment by nitedog** [comment]
Yes, the concern was about click.

We could look at using the two terms interchangeably in the narration. But what would the title for this showcase example be?

**Comment by yatil** [comment]
Brainstorm:
- Large buttons? I know it is not _only_ about buttons, but the term is probably known well.
- Spacious Interaction?
- Spacious Buttons?

**Comment by nitedog** [comment]
Agreed on "Large select areas" per [face-to-face resolutions](https://www.w3.org/2016/03/18-eo-minutes.html#ResolutionSummary)
