### ISSUE TITLE
[Script 8: Text Customization] [eds discretion][minor] - more toast

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#120]
[eds discretion]  As I said in the 26 Feb telecon, I mildly think it would be good to have 3 levels of toasted bread (instead of just 2)(or 4 with one not toasted at all), but do not feel strongly about this at all.

**Comment by nitedog** [comment]
Sorry, that was not clear to me from the discussion. The minutes also mostly talk about 2 people. Can't change that now (would need additional actors and change for filming schedule/plans).
