### ISSUE TITLE
[Overall]

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-showcase-examples#131]
I found the background music to be distracting. On some videos more than others.  Even on the videos where the narration was louder than the background music, I still felt that the background music volume could have been lowered.

"- esential for some, useful for all." - misspelling across all videos

**Comment by nitedog** [comment]
Thank you for the specific suggestion on the music volume. It would be helpful if you have similar observations and suggestions for individual videos, to explain what was distracting to you.
