### ISSUE TITLE
[Keyboard Video] music

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-showcase-examples#132]
Background music very distracting.

**Comment by nitedog** [comment]
Can you say why it was distracting? For example the melody, the instruments, the tact, etc.

**Comment by lakeen** [comment]
In some cases the volume of the music puts it in the foreground and the narration in the background. In some cases they seem to be at the same level, competing with each other. I had a hard time paying attention to what was being said.  I think the volume could go down a lot.

**Comment by nitedog** [comment]
From @yatil 

>  I think the music fits really well (but could be a nudge less loud in some videos)

**Comment by nitedog** [comment]
From Judy:

> Background music in video is very bouncy/staccato and varied in pitch, making it distracting and difficult to follow the voice-over.

**Comment by nitedog** [comment]
From @sharronrush 

> I like this video quite a bit, including the voice, accent and music.

**Comment by nitedog** [comment]
From @bakkenb 

> Music is good.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
