### ISSUE TITLE
[Overall] Streamline, focus message

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#135]
Will leave more detailed comments next week. Overall however I think each section needs the message to be clarified and the delivery of it streamlined and pointing to specifically targeted resources.

**Comment by nitedog** [comment]
1. For some of our topics, there are 1:1 follow-on resources - like a story in How People with Disabilities Use the Web or a tip in Getting Started Tips. But often there aren't any such ready resources, multiple, resources or different ones for each topic. Is it OK to have "further resources" that are very inconsistent, and sometimes without direct relationship?
2. There is also background reading that everyone visiting this resource should be aware of. Would we link these in every section or keep the "learn more" section at the end of the document? Or put it at the start instead?

**Comment by sharronrush** [comment]
I think the "Learn More" section is good and would leave it for general direction.  But since for most of these issues it is only a (very brief) tip of the iceberg, I think we can find resources to support all of them.  I don't think it is a problem that there will be variation in the number of specificity of the supporting resources and would be interested to hear what others think. I am happy to help find suggestions but can't do it for a few days.

**Comment by susanatx** [comment]
Sharron, are suggesting adding links to more info in each video's paragraph?

I'm always for less = more so felt the text was too long. As is, the paragraphs don't really add to what's in the video. Is the intention for the accompanying to text to serve as an intro? Summary? Looking at just "Customizable Text" there are examples of benefits that aren't in the video, e.g. "This also allows content to reflow better on different window and screen sizes, and make it more usable across different devices."

Instead of using these to add more content than is covered in the video or to try and cover the points in the video, let's keep them brief. I imagine we could cut each paragraph down to a couple of sentences. Also, I recommend we change the link text for "learn more..." since it just takes them to another section of the page. They aren't learning more, just skipping to a section with more links. And cut out the tagline after the link.

I need to think about wordsmithing here to give more specific suggestions.

**Comment by sharronrush** [comment]
I think the text is unnecessary and detracts. I think a short bulleted list
to "more about this specific topic"

**Comment by susanatx** [comment]
I just gave a quick example of an edit down on Keyboard Text. On second thought I think we should leave out the link all together. If we can't give them a 1:1 resource for that specific topic, it's not necessary to have the same general link in each paragraph.

**Comment by shawna-slh** [comment]
We need to discuss the approach to the text on the web page. One possibility is under each video:
- transcript text
- additional points (probably bullets)
- specific links

**Comment by nitedog** [comment]
Relates to #137

**Comment by nitedog** [comment]
The sections are now organized in a bulleted list with expand/collapse:
- What does XYZ mean?
- Who depends on this feature?
- What are the additional benefits?
- What needs to happen for this to work?
- Learn more

These items are each either a short paragraph of 2-3 sentences, or a bulleted list (for "who benefits" and "additional benefits").

**Comment by sharronrush** [comment]
Yes, in general I think this is a good approach and will review the details of each support material section in the next couple of days.

**Comment by bakkenb** [comment]
I like the way this is now laid out with bullets. This will help people get to the "more information" that they are particularly interested in. Rather than in the paragraph style, they will know right where to click to find the key information that they need. I know that most of the wording is draft right now, but would like to see the site give a bit more detail in the explanation for "what needs to happen for this to work?"

Still not sure if I like the expand/collapse feature yet. I will have to use the page more to decide.
Nice work!

**Comment by nitedog** [comment]
OK. Great to see support for the overall direction. Seems like we're on the right track.

@bakkenb - do you mean the WAI website or on this particular resource page? Remember that the intended audience is people who are completely new to accessibility, and often also non-technical. How far do we want to drill right upfront? Would this seem too daunting to see a comprehensive guide? Or rather have the "learn more" section to lead people to further resources, if they get interested by the brief summary on this page?

**Comment by susanatx** [comment]
I definitely like this direction. Like Brent I'm questioning the use of expand/collapse here (on this resource, not in general) but I'll need to look at them more closely before I could propose any alternative.

**Comment by bakkenb** [comment]
I did mean on the Web Accessibility Perspectives page. Thank you for reminding of the requirement that this is for non-technical people who are very new to accessibility. I agree that we don't want to get into technical information her or even a technical list of what to do. I was thinking more about how could we answer the question of "what needs to happen for this to work?" in a more conversational way of ...well, this is what needs to happen...   Not getting technical yet, but just a bit more detail (in some cases) than what is there now. 

I will think on this some more as I look over the page in more detail. I am sure others will have more specific opinions about this section. Again, thanks for the reminder of the intended audience.

**Comment by nitedog** [comment]
I took a stab at adding a tad more detail to the keyboard compatibility section ([see the changes](https://github.com/w3c/wai-showcase-examples/commit/fa45168bf0c34b724d09743b26aee9063bbed67f)). I'm hesitant to add more, as we are already getting quite technical. We will also start repeating tutorials and other materials.

Please let me know what you think of this, and of any other sections that your feel are too brief.

**Comment by shawna-slh** [comment]
I really like the approach overall!!! It's much more digestible, and the right type and amount of information.

ftr, I generally do like expand-collapse, when used well. :-) In this iteration, I think there are way too many. If I want to read much of it, I have to do a lot of clicking.

For each section, I'm thinking it would be good to have the first paragraph always visible, and then one expand for all the other information.

(The UI and spacing needs cleanup, but I assume this is a quick prototype only and that is known.)

**Comment by shawna-slh** [comment]
[low/minor]
In the Learn More sections, when there are multiple resources in a category (like under "Text to Speech" which has 2 or 3 in each category), probably nested list would be good.

**Comment by shawna-slh** [comment]
Better with the opening paragraph always visible -- but there's still a lot of clicking with 4 expands for each section. I meant  _one_ expand for each section.

_Not_ this:

> intro paragraph...
> [+] Who depends on this feature?
> [+] What are the additional benefits?
> [+] What needs to happen for this to work?
> [+] Learn more

I meant something like this:

> intro paragraph...
> [+] Who, What, How

or maybe:

> intro paragraph...
> [+] More information

I don't feel super strongly about this (although some people I thin k would be strongly against all those ex-col, like Anna Belle). Hopefully at AccessU we can do some informal usability testing on expand-collapse overall and maybe we use this page as one example?

**Comment by slhenry** [comment]
[medium (for accessibility)] spacing needs fixing for proximity of related information. specifically, more space between sections (after bullets):

[+] Who depends on this feature?
_(could have less space here if wanted)_
       *bullet text...
       *bullet text...
_[need more space here]_
[+] What are the additional benefits?
_(could have less space here if wanted)_
       *bullet text...
       *bullet text...
_[need more space here]_
[+] What needs to happen for this to work?
...

It would also probably be easier to read if those section sub-headings were bold.

**Comment by nitedog** [comment]
I think that would expand an overwhelmingly long list. People may be only interested in specific bits, like how to do this _or_ the learn more resources, but not everything at once. There is an "expand all" for people who want to read a lot at once.

I'm OK with doing testing at AccessU but changing presentation may imply rewriting content. I already had to adapt several sections to show the first paragraph opened :( - though I think this is better now.

**Comment by sharronrush** [comment]
I think it will be fine to get it to a place with the many expand/collapse layers that "we can live with this for now" for the May 17 release. I think the problem is more the presentation - the clunky + sign with the addition of the ugly red line on mouse hover.  

I actually like the fact that I can quickly browse and only get details when I want them.  As we re-think the visual styles with the redesign, this may become less visually intrusive.  +1 to asking for input at AccessU and getting people to comment on the interface but going ahead and using it for now.

**Comment by shawna-slh** [comment]
On 6 May telecon, EOWG agreed to have each video on a separate page. Then I think we should **_not**_ have any expand-collapse on those pages. Probably the sections (Who depends on this feature? What are the additional benefits? What needs to happen for this to work? Learn more) should be [h2]s

**Comment by nitedog** [comment]
Here is a preview for [keyboard compatibility](http://w3c.github.io/wai-showcase-examples/keyboard.html) - @haltersweb, @bakkenb, and everyone esle, what do you think? Note that the "more videos" will be significantly bigger with the thumbnails - are these sub-pages going to be too big without the expand/collapse? Also consider other topics with many more "learn more" resources, like text to speech for example.

**Comment by bakkenb** [comment]
After initial preview of keyboard compatibility, I don't believe we would need to use the expand/collapse on the individual pages. I like how it is all laid out. When the video is on a page by itself with the title at the top, then I know that all content in the headings below is specifically for this video topic. It is easy enough for me to skim those subtopic headings and read more of the text if interested in the heading.

I know you still need to consider text width as it is sort of mixed in this example. I am not sure I like all short width (same width as video player) or long width (entire page). I think I like something in between.

**Comment by nitedog** [comment]
Good point on width. I think we will revert back to full width, which is default WAI design, and revisit that during the redesign process. I could move down the h2 from above the video to the text below it, so that it is separated from the player visually. Thoughts welcome.

**Comment by James-Green** [comment]
This may be the plan already, but I wanted to specify that we should use use actual thumbnail images pulled from each video rather than the blue/green snowy images.

**Comment by nitedog** [comment]
Yes, absolutely! The proposed stills for each video are in the [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).

**Comment by nitedog** [comment]
EOWG f2f sub-group agrees that this thread has been adequately addressed.
