### ISSUE TITLE
[Keyboard Text] Need focus and clarity

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#136]
Suggest edit to something like this:

The video shows a few examples why web sites and applications must support keyboard interaction. Keyboard support is essential for people with physical and visual disabilities who may not be able to use a mouse, for those with injuries such as a broken arm or repetitive stress injuries (RSI), and in other situations where a mouse is not usable. Here are some additional resources about the importance of and techniques for providing keyboard support:
- [Profile of reporter with repetitive stress injury ](https://www.w3.org/WAI/intro/people-use-web/stories#reporter)
- [Web accessibility standard for keyboard interaction](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html)

**Comment by susanatx** [comment]
I like these links better than the link to the general resources section. Can we pull these together for each video?

**Comment by nitedog** [comment]
Relates to #138

**Comment by nitedog** [comment]
This entire section has been reworded taking these suggestions into account.
