### ISSUE TITLE
[Overall] need follow-on resources specific to topic

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#137]
I find in all instances that the text does not provide additional resources specific to the topic which I think will be most useful.

**Comment by nitedog** [comment]
From @susanatx

> The resource link in each paragraph needs to be to more specific, relevant resource or removed altogether. Details in "Overall" on Git Hub.

**Comment by nitedog** [comment]
From @bakkenb 

> For each text section, I would like to see links added to support pages. Would we want to link directly to specific parts of resources, list out specific Success Criteria or specific techniques? Not sure how in depth this resource should go.

**Comment by nitedog** [comment]
From @James-Green

> I also think most people won't read the text but It will help with SEO.

**Comment by nitedog** [comment]
From Howard

> I thought the overall structure was fine but the paragraphs under each video are too wide.

**Comment by bakkenb** [comment]
+1 to too wide text

**Comment by nitedog** [comment]
Follow-on resources aspect addressed by issue #135 . Width aspect will also be addressed.
