### ISSUE TITLE
[Keyboard Text] example of edit down.

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#138]
# As stated in the Overall comments on Sharron's 'Streamline and Focus" issue, I think these could all do with being edited down a bit. Here's an example:

Current:
"Websites, including forms and applications, need to support keyboard interaction. This allows them to be usable by people using on-screen (touch), ergonomic, and specialized keyboards, as well as by voice recognition. This is essential for many people with physical and visual disabilities who may not be able to use a mouse. It is also useful in many other circumstances, such as for people with injuries such as a broken arm or repetitive stress injuries (RSI). It also allows websites to be usable on public terminals (kiosks) without a mouse or when the mouse simply breaks. Learn more about web accessibility - esential for some, useful for all."

Suggested:
"People need to be able to use a website without a mouse. This makes the site functional for some people with physical and visual disabilities who might use specialized keyboards or other input methods. It also could be helpful to those who don't have a disability but can't, or choose not to, use a mouse. " (No link. See the Overall issue I cited above.

**Comment by nitedog** [comment]
Relates to #136

**Comment by nitedog** [comment]
This entire section has been reworded taking these suggestions into account.
