### ISSUE TITLE
[Script 5: Layout and Design] More frustrating things

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#14]
> There are few things in life more frustrating than a poor layout

Might be me, but I have a long list and poor layout is not at the top :)

This may be better expresssed without the superlative approach? Mayby something like:

> Poor layout is extremely frustrating

or

> When something is badly laid out, it is really frustrating

**Comment by bakkenb** [comment]
+1  
That is a good point. I like both versions of the edit, prefer the second a little better.

**Comment by nitedog** [comment]
From Judy:

> Credibility -- "There are few things in life more frustrating than a poor layout" I can think of 100 things more frustrating than poor layout. Could just say "Poor layout can be extremely frustrating, and particularly for people with disabilities, it can be a significant barrier."
>  "ANY web user will get frustrated with bad layout and design" Careful of sweeping statements and generalities to maintain credibility -- no, some people don't even notice bad layout

From James:

> I would be careful about making an overstatement at the beginning of the video and distracting a viewer with the possible fallacy.. "There are few things in life more frustrating than a poor layout" I love the point (especially with the visual), but I'd recommend more careful wording...

**Comment by nitedog** [comment]
Removed.
