### ISSUE TITLE
[Learn More] edit suggestion

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#140]
Edited for more conversational tone:

"Here are some of our web accessibility standards, guidelines, and other resources to help get you started:"

[alternative to "our" could be "WAI's"]

I strongly believe adopting a more conversational voice instead of a third person, detached tone in our resources is crucial to making our site more engaging and widely-referenced by the community at large.

**Comment by nitedog** [comment]
How about this:

> "This website provides a variety of standards, guidelines, and resources to get you started [with web accessibility]:"

I think our primary target audience will not (yet) know "WAI" or who we refer to with "our" (may even feel exclusive like a closed club with "we" and "them").

**Comment by bakkenb** [comment]
+1 to @nitedog

**Comment by nitedog** [comment]
The sentence has been adopted as proposed above.
