### ISSUE TITLE
[Overall] Slower, clearer, longer

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#141]
Overall I think they need to be a little slower and a little longer.

The narration should be slower and a little clearer so it's easier to understand, including for non-native speakers. (A couple places even the native speakers missed words (said, "huh?").) There should be longer pauses between phrases -- especially around certain visuals and before the final phrase ("XYZ, essential for some, useful for all"). In order to be understandable for a large % of our audience, the narration should be such that it might even seem a tad slow for native speakers. I think that is a trade-off that we want to make.

Also some of the visuals need a bit longer time. I think it's fine – even good – that that will make the videos a bit longer overall. Most of the videos need a bit more time to be understandable and get the point across clearly.

(details in comments on each video)

**Comment by nitedog** [comment]
Should be addressed by all the changes noted in comments to the [production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
