### ISSUE TITLE
[Keyboard Video] Narration and visuals are out of sync

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#142]
Narration: "Whether it’s temporarily limited mobility"; visual: person with disability.
Narration: "a permanent physical disability"; visual: person with arm in sling typing.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
