### ISSUE TITLE
[Keyboard Video] Longer scene w/o narration

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#143]
0:22 Visual: "Use your mouse to…"

I totally missed that text the first few times I watched the video. I only noticed it when I freeze framed to write comments.

Stay on it longer, without narration, so people read it.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
