### ISSUE TITLE
[Customization Video] Toast & 2 guys doing what? [low]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#144]
I really like the first visual of 4 difference piece of toast at different levels of toasted-ness! Thanks!
I suggest a little longer on the view with all 4 pieces with the left part not ghosted out. You could shorten the view of the dark and light plates a tad.

At the beginning, the two guys doing nothing with the toaster isn't compelling – actually it's confusing – what are they doing? I think you have footage of someone adjusting the toaster settings. I think that would be good to include. …hum, /me sees that at the end. Possibly do it here, too? Or see what other footage you have for the beginning? Or less on the guys & toaster, and more on the woman trying to read.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
