### ISSUE TITLE
[Customization Video] Narration distract from visuals & vice versa  [MEDIUM]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#145]
UT participant said: "too fast – I didn't get it".
Too much going on with narration and visuals.
[Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

Starting around 0:20, there's too much going on to follow. I suggest having some time when the narration is quiet to let us absorb the visuals. Ideas:
- show plenty of time on her not being able to read after she puts her glasses on – maybe without any narration.
- leave quiet time to read the dialog box -- probably have the narration first, then be quiet while we watch her use the dialog box and we see the result.
- longer of the visual of her being satisfied after she changes the text.

**Comment by shawna-slh** [comment]
Brent says he liked in the audio described version the longer video segment of the woman first struggling to see and then after changing the text being able to read more comfortably.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
