### ISSUE TITLE
[Contrast Video] Simplify beginning & contrast more clear (pun intended) [low-medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#146]
Different signs and cut-backs between person and signs a tad confusing and adds more complexity than is needed to make the point. Probably use fewer different signs and maybe fewer back and forths.

To make the contrast difference between the signs more apparent (that is, have greater contrast ;-), go from good contrast sign to low contrast sign w/o person in between.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
