### ISSUE TITLE
[Contrast Video] Clearer with narration & visuals [low-medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#147]
[Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

Button getting brighter at 0:30 is good – but make it even more noticeable. Probably have the narration first "if it's important… needs to be clear", then be quiet so we can notice the button getting brighter.

**Comment by nitedog** [comment]
From @sharronrush

> This video is muddled, the point is not clear. The guy on the couch seems to have nothing to do with story being told, maybe just stick with the person finding her way on the street.

**Comment by nitedog** [comment]
From @yatil 

> I don’t really understand the scene with the notification (0:36–0:47), I don’t really know what that has to do with good contrasts… That he is able to see the notification? If so, that is very subtle. However I think the shot leaves good breathing room for the narration, so that I’m totally ok with (me not understanding) it.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
