### ISSUE TITLE
[Layout Video] misc [low-medium-high]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#148]
UT participant: "didn't get the main point"

[Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

In the beginning, it's not clear that things are layed out poorly in the kitchen. Need more video of him searching for things, not close up of him getting things out of cabinet and putting on counter.

Rearranging the kitchen doesn't make sense in this cut down version of the story. It's not a big deal, but if we can add a line of text or something to explain it, it would be good – or maybe drop it all together?

Maybe move "This includes clear headings, navigation bars, and consistent styling." to after he opens laptop, not while fast-forwarding around the kitchen.

Love the low vision user with screen magnification and the visual of person with cognitive. I think you can go longer on the scene showing the whole monitor, person's back, and the screen magnification. Also, consider saying "Complex layouts also make finding information difficult or impossible for people with visual disabilities" **before** showing screen magnification (and then a pause in the narration for people to grok the visual).

Take a bit longer showing that a person types in a new web address and longer on the better designed website, especially the top. Pause in the narration for us to grok it's a better design.

Minor: "my camping mug" is distracting. At 0:38 why a close-up of a mug – and it's a different mug from the beginning – and it's a heart mug, which doesn't quite fit character. :-)

**Comment by nitedog** [comment]
From Judy: 

> The kitchen organization and pizza delivery metaphors work nicely in this video.

**Comment by nitedog** [comment]
From @dboudreau

> I feel like the metaphor of the cupboard in this one is a little weaker than the metaphors of the other videos, but it's still really good.

**Comment by nitedog** [comment]
From @yatil 

> Visually there is _a lot_ going on in the kitchen, which underlines the point the video is making, but I wonder if that might be confusing for people. I wonder if the clean-up scene would make more sense after the problem is described.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
