### ISSUE TITLE
[Areas Video] Large Select Areas -> Large Click Targets [high]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#149]
The heading still doesn't work – it's just not clear what it refers to, even with the short video. We need to say "click targets" so people will even understand the point of the video. Anything else is just not clear. The narration and the visuals do a good job of including the broader issues, including tapping touch devices.

**Comment by nitedog** [comment]
From Judy

> Didn't know what "select areas" meant in this context until watched video and realized it was "target areas." How widely is the term "select areas" used?

**Comment by nitedog** [comment]
Working group agreed on "Large Links, Buttons, and Controls".
