### ISSUE TITLE
[Captions Video] Not cancer [HIGH – HIVE]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#150]
Captions big at the end include "… the risk of cancer coming back…". This is a huge issue for some people and just seeing that phrase will elicit significant negatives.
(/me channeling Anna Belle here, too. :-)

Also note that I found those captions distracting from the narration. Not sure the best way to handle that. Maybe just adjust the timing (and include pauses) so the captions don't take attention away from the narration?
[Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

**Comment by nitedog** [comment]
Yes, maybe the pause will help. Maybe also different segment of the captions. But unfortunately it is a video about cancer playing. Difficult to change that now.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
