### ISSUE TITLE
[Captions Video] Main point in visuals and narration [medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#151]
[Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

After narration "captions make videos accessible", pause narration (before going on to "which is also handy for …").  Also longer visual of the person with hearing disability using captions. This is the main point. Let it sink in! :-)

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
