### ISSUE TITLE
[Captions Video] zoom to captions not visible [very low]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#152]
Around 0:22 where it zooms into "Subtitles/CC" – I couldn't read that the first times I looked at the videos (on mobile and then in page w/o resizing) – only could figure it out when I looked carefully in full screen on a large monitor. People with lower vision won't be able to read those letters.

But I don't think it's essential visual, so OK leaving as is if need to.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
