### ISSUE TITLE
[Captions Video] Beginning stop not work [high]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#153]
The beginning doesn't work.

> Narration: "If I stopped talking now you’d have to guess what this film is about."
> Visual: a video with someone else talking.

But we didn't hear that person or know what that film was about before our narrator stopped talking -- so it doesn't matter that our narrator stopped.

To make this work, you'd need to do something like show the video and have the narrator start to explain what the person is saying, and then stop (and pause for longer). Or have the audio portion of the video going, and then stop it.

I'm not sure at this point whether to try to make the idea work, or abandon the idea…

Minor: Visuals are fairly cluttered at the beginning – with the desk clutter and the content on the monitor is cluttered. I wonder about much less/quicker on all that and show the focus on the one video playing sooner?

**Comment by nitedog** [comment]
From @yatil 

> I think the pause after “if I stopped talking” is either too short or too long. I don’t feel the frustration yet. Also the video only shows a video of a woman talking, and even if the narrator says something, he probably wouldn’t say what the woman is saying, so the example is a bit weird. 
>  I think it could be beneficial if there wasn’t a pause at all and the following sentence was different.

**Comment by nitedog** [comment]
From @dboudreau

> I also didn't like the question at the beginning "annoying, isn't it?). I felt as though it wasn't punchy enough. I think we could re-frame it to have more impact.

**Comment by nitedog** [comment]
Or have the narrator say "without audio/sound, you'd have to guess what this film is about"?

**Comment by nitedog** [comment]
From @bakkenb - have the music also stop during this pause.

**Comment by bakkenb** [comment]
Have the music also stop during this pause. Don't have the music start back up until after the longer pause, <b>AND AFTER</b> the narrator says "Frustrating isn’t it? Not knowing what’s going on." Then start the music again.

**Comment by nitedog** [comment]
Noted in comments to the [production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
