### ISSUE TITLE
[Speech Video] Visual disabilities -> blind [high; hive]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#154]
"It’s technology that many people with visual disabilities have been relying on for years." ->
"It’s technology that many people who are blind have been relying on for years."

Rationale: "Visual disabilities" includes blind and low vision. Most people with low vision **do not rely on text to speech**. We need to not propagate misunderstandings about the different user experience and needs of people who are blind versus people with low vision.

(fyi, by some estimates, there are 6+ times more people with low vision than are blind. (WHO) estimates that of the 285 million people worldwide who are visually impaired, 39 million are blind and 246 have low vision; that is, 14% are blind and 86% have low vision. http://www.who.int/mediacentre/factsheets/fs282/en/)

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
