### ISSUE TITLE
[Voice Video] misc [medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#155]
UT: "too cluttered, didn't get it. Too much going on"

Consider more pauses and less overlapping visual activity and narration, per [Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

I think need brief explanation of "voice recognition". Perhaps something like:

> "One of the advances of technology is voice recognition, whether it’s searching the web... ->
> "One of the advances of technology is voice recognition – that is, you can speak to your computer -- whether it’s searching the web...

Give people a little longer to read what she writes at the beginning.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
