### ISSUE TITLE
[Understandable Video] Narration and visuals competing for attention [medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#156]
[Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

Starting at 0:30, I'm focusing on the visual of people typing in a website and miss the narration. Need to pause to let mind focus on one at a time.

Show the clearer website (starting at 0:37) longer. Pause before the tagline/catchphrase.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
