### ISSUE TITLE
[Notifications Video] Make important visuals understandable ;-) [medium-high]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#158]
[Relates to https://github.com/w3c/wai-showcase-examples/issues/141 Slower, clearer, longer]

Longer on the important visuals – the error messages – long enough that people can read them. Also, pause the narration so I can process the visual without the auditory distraction.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
