### ISSUE TITLE
[Overall] title & web accessibility context [medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#159]
[relates to title https://github.com/w3c/wai-showcase-examples/issues/108 & catch phrase https://github.com/w3c/wai-showcase-examples/issues/109 & Slower, clearer, longer https://github.com/w3c/wai-showcase-examples/issues/141]

Issue: Context of Web Accessibility and title/topic of video could use reinforcing in visual &/or narration

Visual: We talked about whether or not to have the title (e.g., "Keyboard Compatibility") visually at the beginning &/or ending. Having seen the videos, I definitely think we need to keep it at the beginning – and I actually think it would be good to repeat it visually at the end. (although it's not super high priority to add it)

Narration: I find the "title" (e.g., Keyboard compatibility) doesn't stand out enough at the end - I miss it before the catch phrase  -- and I think it's important that the viewer get the "title" again. Also, I think the context of "web accessibility" isn't quite strong enough for people who see these videos in the wild (not from the WAI page). I wonder about adding "For web accessibility" before the title & catch phrase, e.g., 

> For web accessibility: Keyboard compatibility -- essential for some, useful for all.

**Comment by nitedog** [comment]
I think we can add the video title both visually and in the narration at the end.

However, I don't really like that addition of "web accessibility". It seems wedged. Besides, most of these accessibility features we describe are not limited to the web only.

How about just "web accessibility -- essential for some, useful for all", _if_ we can add the video title (eg. "keyboard compatibility") right after in the closing? It would then say:

> "web accessibility -- essential for some, useful for all" [switch to end screen] "Keyboard compatibility -- visit w3.org/WAI/Perspectives for tips and information"

**Comment by nitedog** [comment]
Relates to #161

**Comment by nitedog** [comment]
TF tentative decision:

> Web accessibility: essential for some, useful for all
> Visit w3.org/... for more information on XYZ

**Comment by nitedog** [comment]
Noted in comments to the [production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
