### ISSUE TITLE
[Script 5: Layout and Design] Not sure about café scene

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#16]
> Reveal that the whole scene has been in a café where there are plenty of people on computers, tablets and phones – one is clearly perplexed by the website they’re on

I am not sure how the café scene helps to convey the message. Or the following sequence where it is panning to an angry, older user. It seems there is a lot of time invested in this scenario in this video and little showing the benefit to people with disabilities.

**Comment by yatil** [comment]
+1 I think the context change is a bit too much. First it’s a kitchen, then a different kitchen, then a café. Just have the older person enter the kitchen and sit on the table, I think that would be sufficient. (Also, I’m concerned of the complexity to produce the whole scene.)

**Comment by bakkenb** [comment]
I believe the reason the production company suggested this panning idea was to continue to pull the viewer into the video. Unfolding the presentation a bit at a time. Hoping to keep their interest and show the translation of a real world layout of a room to that of a poorly designed web page. Then a larger area like a shop as compared to an entire web site.

I am interested to see what the production manager thinks about these comments however.

**Comment by nitedog** [comment]
It is the same kitchen, not two. As Brent says, the unfolding aspect should be visually appealing. It is quite difficult to glean this from the script only, I guess.

**Comment by AndrewArch** [comment]
clarity from Claudia during teleconf was that the first scene is in a kitchen (poor arrangement then good arrangement), then the screen is in a cafe - transition via zoom into tablet and out again
the current script doesn't do the transition idea justice at this stage - some sketches might help?

**Comment by yatil** [comment]
Thanks for the clarification.

**Comment by nitedog** [comment]
A full-blown storyboard would be difficult at this stage but wording improvements will be made to clarify the transition from the kitchen to the cafe.

**Comment by nitedog** [comment]
Provided further clarification in the script, to reflect this common understanding.
