### ISSUE TITLE
[Overall] Order

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#160]
TF says some considerations on order:
- easy to understand first
- ones with clear mapping to WCAG SC early, then alternate
- separate text-to-speech & voice recognition

_[TF folks feel free to edit!]_

**Comment by shawna-slh** [comment]
Some other considerations for ordering:
- ones with good pointers for more detailed info (e.g., Getting Started Tip, Easy check) nearer the top
- high impact on people with disabilities nearer the top
- better videos with clear messages and metaphors nearer the top

Another idea is putting them under subheadings of POUR. I haven't played with that to see how it would work.

**Comment by nitedog** [comment]
From @susanatx

> What's the reasoning for the current order of the videos? They're listed neither
> alphabetically nor by WCAG SC.

**Comment by nitedog** [comment]
From Judy:

> I didn't understand before reading the text explanation that this was a demo of color contrast and glare inside and outside; I thought it was a demo of two people using a messaging app to communicate their location; so the accessibility point of the video was difficult to figure out. The text on the website took care of that, but others might have the same misunderstanding. Perhaps the order of the video shots could be re-arranged, so that it is more clearly two distinct stories -- one outside, then one inside.

**Comment by yatil** [comment]
I like the randomness of the videos, I also thought that the order worked out nicely for me.

**Comment by bakkenb** [comment]
Start with an easy to consume video to give the viewer a good understanding of how the videos are laid out, then the rest are fine in any order.

**Comment by nitedog** [comment]
After working some more on the text and processing the comments, I think it is best to move the text-to-speech up (and away from voice recognition). I changed it around for preview.

**Comment by nitedog** [comment]
Task force feels happy with the current order.
