### ISSUE TITLE
[Overall] accent

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#165]
From @yatil 

> and I also like the narrators, they sound relatively diverse. I think having some UK accented voices really shows how broad the W3C is (hint: world wide ;-) and we can add more videos with other even more diverse accents later.

**Comment by nitedog** [comment]
From @slhenry 

> I'm fine with the accents. I think better to have UK accents than American accents. Would be nice if they were a bit milder, but I do not think it is a priority at all.

**Comment by nitedog** [comment]
From Judy (for "Keyboard Compatibility")

> Voice-over sounds very clipped British English; if doing further voice-artist work, could be helpful to have a less less regionally distinctive accent.

**Comment by bakkenb** [comment]
I have no problem with the mild UK accents. I like them better than American for these videos.

**Comment by nitedog** [comment]
It is not UK vs US accent, but rather UK vs plainer English ("screen English?"). How much more impact would the video have if it has a more neutral English than any particular accent?

**Comment by nitedog** [comment]
Agreement to go with the current narrators. More care will be taking for all the re-takes and for the audio descriptions.
