### ISSUE TITLE
[General/minor] Too much narration?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-showcase-examples#17]
From reading the scenes feel very dependent on the narration. I don’t have enough knowledge of film-making to know if that is only a feeling from reading the scripts or if this is a valid concern, but I wanted to let you know.

One example: In Script 1/Scene 3 the narration is “Frustrating isn’t it? Not knowing what’s going on”. It would be really cool if the viewer had the impression that is frustrating without actually telling them.

**Comment by yatil** [comment]
Another example for redundant narration in [Script 6: Notifications and Feedback](http://w3c.github.io/wai-showcase-examples/script6.html).

> **Narration:** Unclear instructions - what a nightmare!  
> **Visuals:** We see someone trying to build a piece of flat pack furniture but two bits just will not connect – they end up tearing the instructions in half.

Also “Unclear instructions - what a nightmare!” reminds me of 90s TV commercials…

**Comment by nitedog** [comment]
@yatil - substantial changes have been made, do you still have this concern?

**Comment by yatil** [comment]
I think it got much better and am confident that it will work out in production. So no concern left. Feel free to close the issue.

**Comment by nitedog** [comment]
Thanks for confirming. Feel free to reopen if needed.
