### ISSUE TITLE
[Captions Text] fluency

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#172]
From @bakkenb

> Is the following statement true: "Captions are useful for people who are not fluent in the language," This is only true if captions are provided in the native language that is different than the language used in the video. If not provided, then captions are not "more" useful than the narration to a non-fluent user. Don't know if this phrase should be dropped or reworked somehow.

**Comment by nitedog** [comment]
Yes, it does somewhat - to see and hear at the same time. But that may not be easily apparent without further explanation and should be revised.

**Comment by bakkenb** [comment]
That makes sense. Thank you for the explanation. Yes, further explanation on that would be helpful.

**Comment by nitedog** [comment]
This has been clarified in the updated text.
