### ISSUE TITLE
[Customization Video] metaphor

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#175]
From @sharronrush

> Hey, the toast worked out as a metaphor...good!

**Comment by nitedog** [comment]
From @susansatx 

> We covered this in earlier drafts of scripts and I understand it's too late to change but I
> still don't think the toast metaphor makes sense. The older man has dark toast in the
> first and the last scene. It isn't clear how any adjustments have helped him. Not jarring,
> just visuals that don't seem to add anything.

**Comment by bakkenb** [comment]
Toast Good... I like toast.  :)

**Comment by nitedog** [comment]
We can't really change the metaphor at this stage but some of the edits in the next version may make the analogy more apparent.
