### ISSUE TITLE
[Speech Video] title not spoken

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#177]
From @dboudreau 

> The title of that video does not get announced as the video starts. This is the only one where it had been forgotten. I wold expect the video to start with the narrator announcing "Text to speech" (before we start hearing the synthesized voice).

**Comment by bakkenb** [comment]
I noticed this too and it bothered me a little. Then I realized it was because we wanted to start with the synthesized voice to announce what it was about. I think I am okay either way on this issue.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
