### ISSUE TITLE
[Notifications] cuckoo clock

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#185]
From Judy 

> The cuckoo clock doesn't seem to help tell the story on this one -- it even seems a bit annoying, though I'm not sure why; whereas the other visual examples seem to work well. Not a big issue, but it was the only part of the videos that I found vaguely annoying.

**Comment by bakkenb** [comment]
I think that was kind of the whole purpose of the cuckoo clock not working. To annoy and make people uncomfortable like when a notification is not present or feedback is lacking, it is annoying or confusing to most.

**Comment by nitedog** [comment]
Cannot change this analogy now, if that's the problem. Otherwise the edits in the next release may help clarify the message and point of the cuckoo clock a bit more.
