### ISSUE TITLE
[Notifications Video] more time

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#188]
From @yatil 

> Really, really minor: I think the initial cuckoo shot could use some more time, especially zooming out from the hands to reveal the door where nothing is happening.

**Comment by bakkenb** [comment]
Agree with @yatil about this. This could also help slow down the narration at the beginning.

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
