### ISSUE TITLE
[Notifications Video] thumbnail

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#190]
From @bakkenb 

> Don't use the image of the coo-coo bird as the thumbnail for the video. Just the clock without the bird showing. Takes away from the anticipation being built at the beginning if they see it before the video starts.

**Comment by nitedog** [comment]
Actually one could argue the exact opposite too - seeing the bird in the thumbnail raises your expectation that it should come out as the hands approach 12...

**Comment by bakkenb** [comment]
I will consider. Thanks

**Comment by nitedog** [comment]
How about the hands of the clock approaching 12 sharp?

**Comment by nitedog** [comment]
Noted in [comments to the production company](https://www.w3.org/WAI/EO/wiki/Showcase_Examples_with_Videos/Second_Cut).
