### ISSUE TITLE
[Learn] contents

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#191]
From Judy 

> It seems a bit odd to click the link for "learn more about..." and just end up on the bottom of a page.

**Comment by nitedog** [comment]
From @sharronrush 

> The section is fine as is however as noted, the previous sections need more specific links to support materials for each topic.

**Comment by nitedog** [comment]
From @yatil 

> Is that all we’re planning to point people to? If so, we should add more concrete advice to the individual videos asap. I think each video section should (not now but in the future) answer the question “What can I do about it?”

**Comment by nitedog** [comment]
Each section now has a specific list of resources. These and other resources are listed at the bottom of the page for easier overview and referencing.

**Comment by yatil** [comment]
Great work!
