### ISSUE TITLE
Voice Recognition with Video Description

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-showcase-examples#194]
The voice of the man searching by voice and the man trying to "Submit" sound so far in the background we almost miss what they are doing.  I would bring their voices more into the foreground.

Also, I'd like to make sure the video description and the narration are on the same audio level.  Right now the video description sounds louder than the narration.

**Comment by nitedog** [comment]
This is a temporary recording. Sound levels will be adjusted.
