### ISSUE TITLE
Notifications with Video Description

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-showcase-examples#196]
at 0:18 Video Descr says "The door for the cuco clock is in focus but nothing is happening".

I think this can be changed to drop the info about the door being in focus and state more clearly the problem.  Something like:

"The clock reaches noon but the cuco bird does not pop out of its door to signal the time"

Also, at the end of the video we should hear the cuco sound more loudly.

**Comment by nitedog** [comment]
Changed to "The hands on a cuckoo clock reach noon but the cuckoo bird does not pop out of its door to signal the time."
