### ISSUE TITLE
Keyboard Compatibility: What needs to happen for this to work

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-showcase-examples#198]
This should have more detail.  My concern with saying "Often nothing" is misleading because it's one of the biggest issues we find in development.  How about something like this:

"Native HTML form elements, links and buttons work with the keyboard by default.  Problems arise when custom-made controls, css styles, and scripts that control interaction break this compatibility."

Also, not sure what the sentence below means.  We might want to reword for clarity:

"Special attention to keyboard use is also required to ensure the flow between controls, for example in forms, menus, and applications."

**Comment by bakkenb** [comment]
I was thinking the same thing for this section. I worry that if we say "Often nothing" to start the statement, then most developers may just move on to the next video/issue/topic thinking they don't need to do anything for Keyboard access without reading more about the issue.

**Comment by nitedog** [comment]
Changed to:

> Native HTML controls, like links, buttons, and form elements, work with the keyboard by default. Problems arise when custom-made controls, CSS styles, and scripts that control interaction break this compatibility. Also the navigation between multiple controls could cause barriers. For example, when the order of the controls in the source code does not match the visual presentation, or when there are too many controls without a way to jump between groups of related controls. Such issues occur particularly in forms, menus, and applications with many controls.
