### ISSUE TITLE
Text to Speech: What needs to happen for this to work?

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-showcase-examples#199]
I suggest some edits as shown below for better clarity

"Many computers and mobile devices today have built in text to speech software. Additionally, people with disabilities may use specialized text to speech software called screen readers.

Using semantic HTML markup for structures such as headings, paragraphs, lists, forms, and tables is essential for text-to-speech to work. Also, text alternatives are necessary for images, icons, and other non-text content."

**Comment by nitedog** [comment]
Updated as suggested, thanks.
