### ISSUE TITLE
[scenarios] sign language

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#2]
From George Heake : 

Within the hearing disabilities scenarios I think ASL an other versions of International types of sign language should be developed into the scenarios in addition to captioning.

**Comment by haltersweb** [comment]
I like the idea of ASL and think we can follow Comcast's example: http://corporate.comcast.com/comcast-voices/comcast-launches-american-sign-language-tutorial-videos-for-closed-captioning-settings

**Comment by haltersweb** [comment]
George, do you mean in all the videos along with captioning we have something like a little window showing someone signing in ASL.

**Comment by nitedog** [comment]
Videos do not include sign language anymore.
