### ISSUE TITLE
[Script 6: Notifications and Feedback] Sequence confused

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#20]
Sequence 6 pulls out to show a confused user, but the previous sequence shows an understanding user. Not sure that these would flow well together.

**Comment by nitedog** [comment]
From Adina:

> I'm confused about scene 6. If in scene 5 the confusing error message was changed to something understandable but then in scene 6 we pull out to reveal elderly studying it and getting confused why is he confused if the error message in screen 5 had already been fixed? Maybe scene 6 should be a scene with a different person than scene 5.

**Comment by nitedog** [comment]
Script has been revised accordingly.
