### ISSUE TITLE
Bullet and directives for the "What needs to happen for this to work" section

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-showcase-examples#201]
People often want to swoop in and get a couple of "to-dos".

Therefore I would change the way the wording is done for the "What needs to happen for this to work" section.

I suggest we give bulleted lists of directives that are short, maybe 3-5 words each.

**Comment by nitedog** [comment]
I'm all for bullets but need to check but I'm not sure how well this would work for all the sections. For example, your suggested rewrites in issue #198 would not work and we would need a completely different approach - "Native HTML ... work with the keyboard by default" is not actionable and would likely drop. This would be unfortunate. Also the sentence "Special attention to keyboard use is also required to ensure the flow between controls, for example in forms, menus, and applications" would either become a hugely long list (of techniques?) or boil down to nothing. Do you think it would work well for this and other sections if we get down to it in detail?

**Comment by nitedog** [comment]
Decision at EOWG f2f on 11 May: Content doesn't always lend itself to bulleted list. Leave it as-is for now.
