### ISSUE TITLE
Notifications and Feedback: What needs to happen for this to work?

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-showcase-examples#203]
Since I have rarely, if ever found a developer using an internal error code for an error I would take a different tactic: talk about simple, clear language.  Talk about the need for a confirmation when an action is taken.  Talk about making sure screen-readers announce when a change is made to a current screen.

For example:

"Use clear, simple language to make error messages more understandable. For example, describe how to fix the error.  If a form has been submitted make sure to follow it with a confirmation message.  If a change is being made on the screen, such as the appearance of a loading spinner, or new content being injected, make sure screen readers alert the user to this change."

**Comment by nitedog** [comment]
Updated as suggested, only changed "make sure screen readers alert the user to this change" to "make sure that users are alerted to this change" -- not only screen reader users need to be alerted. Also, we should avoid terms such as "screen readers", which may not be known to our primary target audience (absolute accessibility newbies).
