### ISSUE TITLE
[Priority] expand/collapse spacing

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#204]
From @slhenry (relates to keeping expand/collapse in issue #135):

> [medium (for accessibility)] spacing needs fixing for proximity of related information. specifically, more space between sections (after bullets):
> 
> [+] Who depends on this feature?
> (could have less space here if wanted)
> *bullet text...
> *bullet text...
> [need more space here]
> [+] What are the additional benefits?
> (could have less space here if wanted)
> *bullet text...
> *bullet text...
> [need more space here]
> [+] What needs to happen for this to work?
> ...
> 
> It would also probably be easier to read if those section sub-headings were bold.

**Comment by nitedog** [comment]
I'd prefer not to play around with the space between level 1 and 2 bullets. Adding a bit more space to level 2 bullets makes sense.

@yatil can you please help when you get the chance?

**Comment by yatil** [comment]
> Adding a bit more space to level 2 bullets makes sense.

Do you mean between the individual bullets or after the level 2 bullets.

**Comment by nitedog** [comment]
The spacing between the individual level 2 bullets - see @slhenry's description above.

**Comment by yatil** [comment]
That’s why I asked, because @slhenry talks about the space _between sections_, not between bullets. Anyhow, I can add space between bullets and also make the headers bold, if that is wanted.

**Comment by yatil** [comment]
I have made some changes, please provide feedback.

**Comment by nitedog** [comment]
Expand/collapse has been completely removed in favor of splitting the page into multiple sub-pages.
