### ISSUE TITLE
Add GitHub contribution panel at bottom

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#205]
I mean the box starting with "We welcome your ideas ..."

**Comment by nitedog** [comment]
On each page?

**Comment by shawna-slh** [comment]
hum -- I guess.

With extra space between the bottom of the content and the start of the panel. (e.g., [Improving ](http://w3c.github.io/wai-planning-and-implementation/improving#plan) needs more space; like [this has more space](https://www.w3.org/WAI/gettingstarted/tips/writing.html#learn-more-about-accessibility))

[FUTURE: We probably want to redesign that panel to be a little less big. Or maybe have two versions of it.]

**Comment by nitedog** [comment]
Done.
