### ISSUE TITLE
left navigation bar naming

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#207]
How is the naming in the left navigation bar?
1. Main resource name: "Impact and Benefits" - alternatively "Perspectives"?
2. Sub-page names: "Keyboard", "Contrast", "Layout", ... rather than full name to avoid clutter - OK or prefer two-word title like "Keyboard Compatibility", "Good Contrast", "Layout & Design", ...?

**Comment by bakkenb** [comment]
I like it as is (single word sub-page titles) , but could we add a word to the main resource name?  
Suggest "Impact and Benefits (videos)"
I think this will catch peoples attention that there are videos here to watch. Something new on WAI.

**Comment by nitedog** [comment]
Good point about adding "videos" to the handle - not many people expect to see videos on the WAI website. But this would likely wrap on most configurations - better to avoid wrapping if possible. I was thinking of maybe:
- "Perspectives Videos" (long)
- "Intro Videos" (colloquial)
- "Impact Videos"
- "Benefits Videos"
- "Explore Videos"

**Comment by nitedog** [comment]
Changed to "Impact & Benefits Videos". That is, with ampersand and without the brackets from @bakkenb's suggestion to make it fit.
