### ISSUE TITLE
[Priority] various spelling and grammar corrections

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-showcase-examples#208]
I've added suggested changes in [ ].
http://w3c.github.io/wai-showcase-examples/layout.html
### Who depends on this feature?

• People with low vision who are using screen magnification and only seeing a portion of the screen at a time;
• People with cognitive and learning disabilities who often need clarify [clarity] and consistency to orient themselves on a website.
### What needs to happen for this to work?

Employing [Employ] a functional design with appropriate structure and placement. For example, by grouping related input and controls on a form, and provding [provide] headers to identify such groups. This includes in the markup coding and visually. Also the consistency of presentation and behavior of web page components is important.

**suggest rewrite. It is confusing.**

**Possibility:**
Develop a functional design with appropriate structure and content placement.  For example, grouping related input and controls on a form and including headings to identify such groups’ visual structure are important. Also, providing structure in the markup and consistency of component behavior and presentation are equally important. 

http://w3c.github.io/wai-showcase-examples/large.html
### Who depends on this feature?

• People with physical disabilities who have reduced dexterity;
• People with chronical [chronic] conditions, such as repetitive stress injuries (RSI), who need to avoid excessive movement.

http://w3c.github.io/wai-showcase-examples/understandable.html
### What is Understandable Content?

Content needs to [should] be easy to follow and understand [understood] by the majority of the target audience.

**Comment by nitedog** [comment]
Comments addressed either directly or through other rewrites.
