### ISSUE TITLE
[Script 7: Large Click Areas] Not sure about tick and window example

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#22]
I don't know that I can envisage closing a window on a tablet when trying to click a tick.

Perhaps trying to open wee menu icon and closing, although looking at my iPad even that might be a stretch.

**Comment by yatil** [comment]
I agree, this is unlikely to happen. Maybe closing a lightbox and missing or something like that. Or having small buttons for next step on the knitting website…

**Comment by nitedog** [comment]
Script has been changed accordingly.
