### ISSUE TITLE
[medium] WCAG - write out and link to Overview

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#222]
maybe like this https://github.com/w3c/wai-showcase-examples/pull/221/files

rationale: many/most of intended audience don't know it

**Comment by nitedog** [comment]
Just that this section is now getting quite convoluted and overwhelming for these audience :/

**Comment by nitedog** [comment]
Resolution to change to "Web Content Accessibility Guidelines (WCAG Overview) - see [thread on remaining issues](https://lists.w3.org/Archives/Public/wai-eo-editors/2016May/thread.html#msg15)

**Comment by bakkenb** [comment]
+1

**Comment by nitedog** [comment]
Changed as agreed to in the thread.
