### ISSUE TITLE
[low] punctuation of bullets

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#225]
for the bullets under "Who depends on this feature?" and "What are the additional benefits?"

probably have _no_ punctuation at the end -- **or** periods -- (not semicolons)

**Comment by bakkenb** [comment]
I agree. I would use periods since some of those are sentences with commas in them. Since commas are present, you should end with a period as they are not simple phrases.

**Comment by nitedog** [comment]
Using fulls tops (periods) now.
