### ISSUE TITLE
[Perspectives - Customizable] Needs more clarity

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-showcase-examples#228]
In the "What is Customizable Text" section the last two sentences are not really tied to the issue. 

> Many web browsers provide customization options, though sometimes they are not easily findable. Some web browser plug-ins and mobile applications do not provide or adhere to such settings.

Reword so that these two sentences are tied to one of the two things below:
- Being able to customize text
- Access barrier to not being able to customize text

Right now those two sentences don't mean anything to me except the fact that browsers have options which sometimes are hard to find, and that plug-ins and apps don't adhere to settings (what settings).

Please add for clarity.

**Comment by nitedog** [comment]
Addressed through edits provided by @slhenry.
