### ISSUE TITLE
[Script 7: Large Click Areas] Too many especially

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#23]
Sequence 5 and 6 seem to have lots of 'especially's and I think the text in 6 seems to stop quite abruptly.

**Comment by bakkenb** [comment]
Couple of Suggestions:
- "Especially on mobile, and even more so when the user might be moving around at the time"
- "Even more so on a mobile device, especially when the user might be moving around at the time"

Any more ideas?

**Comment by iadawn** [comment]
> Even more so on a mobile device when the user might be moving around a lot

**Comment by nitedog** [comment]
Script has been changed accordingly.
