### ISSUE TITLE
[all] Learn More in general on sub-pages?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#233]
On the Overview page, we have "Learn More about Web Accessibility" with general links.

On each sub-page, we have "Learn more" with specific links for that topic.

On each sub-page, do we want to have two sections:
- Learn more about [topic]
- Learn More about Web Accessibility in General   [or Overall or such]
  ?

If so, maybe collapsed on opening with expand option?

[priority for Tue: medium-low. priority for in May: medium-high]

**Comment by nitedog** [comment]
As this is posed as a question, what is the level of priority for you - before or after publication?

**Comment by bakkenb** [comment]
This is low-medium for me. What about repeating the "Learn More about Web Accessibility" section from the main page on each sub-page UNDER the other video thumbnails, like where it is on the overview page so that it is separated from the other Learn More section.

**Comment by nitedog** [comment]
From discussion with @slhenry, this can happen after the launch (medium-low priority for now but then high right after publication).

**Comment by shawna-slh** [comment]
I just realized that most of these resources are already included in the specific links -- so I withdraw my idea of repeating the general links.

I mildly support adding a link to the Accessibility Intro.

**Comment by nitedog** [comment]
EOWG took a resolution to keep the pages as is, to avoid adding clutter.
