### ISSUE TITLE
[low]  [Perspectives - Large] delete RSI from "Who depends on this feature?"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#239]
Who depends on this feature?:  "People with chronic conditions, such as repetitive stress injuries (RSI), who need to avoid excessive movement." 

Seems a bit of a stretch to say they _depend_ on this. I'm tempted to suggest deleting it here...

**Comment by nitedog** [comment]
I think "who need to avoid excessive movement" clarifies the dependency well enough. I would prefer to further tweak the wording than to drop this target group from the beneficiaries altogether.

**Comment by chaals** [comment]
People with a condition where they want to minimise movement will often benefit from **smaller** gaps between things - the exact opposite requirement for people with dexterity issues.

People with large fingers, like me, or with no fingers, are another group who seriously need this. I don't know that "large fingers" is widely considered a disability in medical models, but it does fit the functional model of disability in touch interfaces.

**Comment by nitedog** [comment]
OK, so the "who need to avoid excessive movement" seems wrong in this statement, as people actually need to bridge bigger gaps of and between page elements (which can be alleviated by appropriate mouse/pointer settings).

Yet the question still stands - do we keep or remove the entire statement? In my own experience, it seems that more generous sizing and spacing of active elements (buttons, links, etc) is less straining. Do others agree with:
- People with chronic conditions, such as repetitive stress injuries (RSI), who need to avoid strain from accurate movement of the mouse.

**Comment by chaals** [comment]
It's not obvious that the target group you identify actually benefits. Making an incorrect statement, or one that _prima facie_ seems likely to be incorrect, is a way to reduce the value of the whole exercise.

So you should remove the RSI example, and if necessary add a different example.

**Comment by nitedog** [comment]
OK, removed.
