### ISSUE TITLE
[all] superfluous attributes (esp aria)?

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#247]
Do we still need these aria attributes?

> &lt;main id="main" role="main"&gt;
> &lt;aside class="side-box contribute" role="complementary"&gt;
> &lt;footer id="footer" role="contentinfo"&gt;

We also still have a "name" attribute for historic reasons - OK to remove now?

> &lt;a id="skip" name="skip"&gt;

**Comment by nitedog** [comment]
@yatil @susanatx @vuxcaleb @James-Green any thoughts on this issue? Given we are using HTML5, do we still need the redundant ARIA attributes? Anyone know about the accessibility support for these?

**Comment by yatil** [comment]
We will change some of the surrounding HTML anyways with the site redesign. The [support for HTML5 elements](http://caniuse.com/#feat=html5semantic) looks rather good apart from OldIE – The only difference its the later introduced main element whose semantics are not supported by ModernIE (but by Edge) and Opera Mini.

My personal opinion is to stop using the ARIA attributes, including role="main". The name attribute on the a can safely be removed. (In the future we might want to get rid of the `<a id="skip">` as well and link directly to the `#main` element, but we first have to add a mechanism for fixing that long standing chrome bug that only jumps there visually but not the focus.

**Comment by susanatx** [comment]
I agree with dropping the aria roles.

**Comment by lakeen** [comment]
I also agree with dropping the aria roles.

**Comment by James-Green** [comment]
I don't agree at this point.  I would like to see current research about support and am happy to discuss, but will remind everyone that WAI EO is in a unique position and should carefully consider how this could be seen by those that we are trying to educate and encourage to use ARIA.   Deciding that part of ARIA isn't necessary anymore (especially when using it poses no significant burden to use) shouldn't be a light decision.

**Comment by nitedog** [comment]
The WAI-ARIA spec says:

> It is not appropriate to create objects with style and script when the host language provides a semantic element for that type of objects. While WAI-ARIA can improve the accessibility of these objects, accessibility is best provided by allowing the user agent to handle the object natively. For example, it's better to use an h1 element in HTML than to use the heading role on a div element.

The question is, whether the elements &lt;main&gt;, &lt;aside&gt;, and &lt;footer&gt; are adequately supported by assistive technology.

**Comment by susanatx** [comment]
@James-Green  I've always looked at the use of roles in those HTML5 tags as a stop gap. It's not a habit I consider worth encouraging if browser support catches up with HTML5. I agree that we need to provide education on use of ARIA but part of its misuse is using it too often. ARIA should supplement accessible mark-up when native elements aren't sufficient. In this case, it isn't the native elements that are lacking; it's the user agents.

Current versions of all browsers listed here at least have partial support. Except for IE products and two mobile browsers, all support the HTML5 semantic elements at least at current version and two back: http://caniuse.com/#feat=html5semantic

**Comment by yatil** [comment]
I agree with @susanatx, especially as people visiting the WAI site are usually quite forward thinking and using current browsers. 

I think we should remove the roles from all elements but the main role from the `<main>` element. The latter needs the ARIA for support in IE11 and we’re not ready yet to drop that browser – especially as a lot of assistive technologies depend on IE9-11.

**Comment by nitedog** [comment]
Thanks for the valuable data @susanatx. Are there AT aspects to consider other than browser support?

PS: For the record, I disagree with the assumption "people visiting the WAI site are usually quite forward thinking and using current browsers". I agree with @yatil's  conclusion, though ;)

**Comment by yatil** [comment]
If my assumption is not right, my conclusion isn’t and we should leave the ARIA attributes in there.

**Comment by susanatx** [comment]
I've asked my colleagues if anyone knows of a similar site/resource that compares AT support. Like @nitedog said, that's key. But at some point you have to decide when to stop accommodating for browsers that don't support standards. Most places I've worked (including government) go with "current + 2 back." Analytics are very helpful here too.

@yatil remind me, are we talking about the site redesign or a specific resource? If the former, than I strongly suggest we eliminate the redundancy. Browser support is high enough now that the very few cases where there are problems will likely no longer be by the time we're finished. If AT support is way behind browsers, then yes, it would be worth leaving in.

**Comment by yatil** [comment]
It is about this resource (the WAI perspectives), @susanatx.

**Comment by sharronrush** [comment]
I agree with dropping the aria roles

**Comment by dboudreau** [comment]
In my opinion, it's still a little early to be entirely confident about dropping the ARIA roles. It is true that support in recent versions of AT (+/2 versions back for VO, Jaws & NVDA) has been rather consistent, but I'm just not convinced the community updates and keeps up with recent versions that much. The user agents that do support the semantics of new HTML5 elements will simply ignore the ARIA roles when they are found to duplicate the information already conveyed by the HTML5 element. Some older technology might not. It feels safe to keep them in there for now, but I'm a worrier. :)

I can support dropping them as well, but I do feel like it's a little early still.

**Comment by hkramer** [comment]
I also think it's too early to drop the ARIA roles. They're still useful as I understand it, particularly for older browser versions that do not support the new HTML5 tags. I'd err on the side of caution.

**Comment by yatil** [comment]
My understanding is that browsers that don’t understand the HTML5 elements are also not understanding ARIA really well. The [WAI-ARIA implementation report](http://www.w3.org/WAI/ARIA/1.0/CR/implementation-report) tested for IE9+ – Which also support HTML5 elements (but `<main>`). I don’t know or think that this has any significance for this discussion, but the browser baseline issue if directly affecting the WAI Site TF work (and might prompt us to update multiple recent resources, including this one [HTML5 video support, for example], to make them way backwards compatible).

**Comment by dboudreau** [comment]
I've always been too lazy to actually research it, but basic adoption of ARIA components like landmark roles was one of the first things that screen readers implemented from the WAI-ARIA specification a couple of years ago. That was before we had reached a first, stable version of HTML5 with the new stucturing elements like main, footer, header, etc. So my understanding has always been that there's a gap of maybe 2-3 versions where there was somewhat decent support for landmark roles, but yet, no support for HTML5 stucturing elements. Most AT are completely caught up on both now, but I'm always rooting for the underdogs - in the case, folks who are stuck somewhere in old ATversionland. I realize we need to move forward at some point, but I don't know if that time has come yet. Hence my hesitation.

**Comment by yatil** [comment]
/me is happy to add/keep the attributes – I don’t think they hurt… (but as I hinted above we need some common baseline that we decide on and need to follow through with all our resources)

**Comment by nitedog** [comment]
I understand that keeping these WAI-ARIA attributes does not cause issues of duplicate announcement when the native hTML5 elements are support - the object is only communicated once to the AT by the browser. If that is the case, then maybe we should keep the attributes for now, and revisit this issue more thoroughly during the redesign?

**Comment by sharronrush** [comment]
+1 Shadi, good plan!

On Thu, Jun 30, 2016 at 8:31 AM, Shadi Abou-Zahra notifications@github.com
wrote:

> I understand that keeping these WAI-ARIA attributes does not cause issues
> of duplicate announcement when the native hTML5 elements are support - the
> object is only communicated once to the AT by the browser. If that is the
> case, then maybe we should keep the attributes for now, and revisit this
> issue more thoroughly during the redesign?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/w3c/wai-showcase-examples/issues/247#issuecomment-229658669,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGqv0_HWlfrvOILD7bWr6DIE0m2-A2ptks5qQ8VKgaJpZM4Ie6_S
> .

## 

Sharron Rush | Executive Director | Knowbility.org | @knowbility
_Equal access to technology for people with disabilities_

**Comment by susanatx** [comment]
+1 @nitedog

**Comment by nitedog** [comment]
Will leave as-is for now.
