### ISSUE TITLE
[Player] captions nearly disappear with low contrast

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#248]
Happening in Chrome, Firefox, & IE. Probably a player bug.

When I page zoom, it's like there's a semi-transparent gray bar from the bottom which makes insufficient contrast. The gray bar changes height with zoom -- so sometimes only a little at the bottom, and sometimes the whole text it masked.

<img width="447" alt="captions-gray" src="https://cloud.githubusercontent.com/assets/6991814/15343562/5b33dbd8-1c63-11e6-8048-5f2e0345d36a.png">

**Comment by yatil** [comment]
I was not able to reproduce, @slhenry, can you try the new version of the player at w3c.github.io/wai-showcase-examples/Overview.html and see if it has changed for you?

**Comment by shawna-slh** [comment]
I can't either. Hopefully bug fixed. ;-)
