### ISSUE TITLE
[Player] wrong aspect ratios before play

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#249]
The player has a 4:3? aspect ratio, and when the movie starts playing, there is empty space above and below the film. Also the poster image appears squished.
![screen shot 2016-05-18 at 09 28 02](https://cloud.githubusercontent.com/assets/7383985/15358623/84b1bbae-1d05-11e6-8cd8-7780d7543a9e.png)

**Comment by yatil** [comment]
This should be fixed in the dev version at http://w3c.github.io/wai-showcase-examples/Overview.html

**Comment by nitedog** [comment]
It is! Thanks!
