### ISSUE TITLE
[Script 8: Text Customization] Reflective of dyslexia

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#25]
I am not sure about the example with dyslexia. The narrative talks about layout but the visuals only suggests a single word.

Also, I am not sure that 'jumbled text' is entirely descriptive how people with dyslexia perceive. I think I would want to avoid the risk of trivialising or making it look silly.

Perhaps rather than focusing on the same sign, focus on the menu?

**Comment by nitedog** [comment]
Script has been revised and this example has been removed.
