### ISSUE TITLE
[Player] no play button on the poster image

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#250]
When the player first loads, you have to press the play button and cannot just click on the poster image to start the video (Firefox).

**Comment by yatil** [comment]
This might have to do with the youtube embed. Deferring to @terrill

**Comment by terrill** [comment]
Thanks @nitedog for pointing this out. It's an Able Player bug that occurs when you add a poster attribute to a YouTube video. The poster image is an overlay that is masking YouTube's normally clickable video. Here's how it works if you omit the poster attribute: 
http://ableplayer.github.io/ableplayer/demos/youtube.html

My recommendation would be to omit the poster attribute for now and set your preferred default image on YouTube.

**Comment by nitedog** [comment]
Thanks @terrill, we will proceed that way, then.

**Comment by shawna-slh** [comment]
I set the "thumbnail" image in YouTube when I uploaded them.
https://www.youtube.com/channel/UCU6ljj3m1fglIPjSjs2DpRA/videos?sort=dd&shelf_id=0&view=0

 I guess we just need to remove the poster image from the embedding.

**Comment by nitedog** [comment]
Thanks @slhenry, poster removed from player.
