### ISSUE TITLE
[all] Provide captions files & encourage translations

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-showcase-examples#255]
near-future consideration - make captions files available and invite translations
Could happen while we finalise page text and be made available ahead of inviting translations of the resources pages.

**Comment by shawna-slh** [comment]
fyi, Current Setting in YouTube allows people to upload captions/subtitle files.

**Comment by nitedog** [comment]
The scripts and caption files are also on GitHub. Not sure how to announce and promote. Maybe after the current EOWG review run?
