### ISSUE TITLE
[all] Reword "Mobile" heading under Learn More section

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#258]
The sub-heading "mobile" alone isn't sufficient.  I suggest "Mobile Applicability," "Mobile Context," "Mobile Overlap," or similar.

These links are on Keyboard, Clear Layout, Understandable Content, Colors with Good Contrast, and  Video Captions. (Called Mobile Web Design on Text to Speech.)

**Comment by bakkenb** [comment]
+1
I like "Mobile Applicability." Some more ideas:
- Mobile Accessibility
- Mobile Design
- Mobile Considerations

**Comment by nitedog** [comment]
Also agree with "Mobile Applicability" (it is shorter and easier than "considerations"). Will edit accordingly.
