### ISSUE TITLE
[all] "Up" link on individual pages

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#259]
The "Up" tag before "Overview" is confusing. Can we rename it or, better yet, remove it? The link doesn't really make sense at all stuck between previous/next.

**Comment by bakkenb** [comment]
What about using "Home"

**Comment by nitedog** [comment]
How about just "Overview" and in bold (to match "Previous" and "Next" also in bold)?

**Comment by susanatx** [comment]
That work for me.

**Comment by bakkenb** [comment]
That works for me too.
