### ISSUE TITLE
[Script 8: Text Customization] Analogy doesn't work

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#26]
In sequence 5 an analogy is made between changing content on a webpage and a person physically changing a sign. I am not sure that this is realistic or conveys the issue that well.

**Comment by yatil** [comment]
👍 

I think using the menu with bad font, lighting, colors would be much easier to understand (but, point taken much more ordinary).

**Comment by shawna-slh** [comment]
I agree this analogy doesn't work. (Good try, though, as it is clever. :-)

In real life, we do not change physical signs. Electronically we can change text.

People might think it's totally absurd to think of changing a physical sign to meet individual needs and then think it's equally absurd to change electronic text. :(

**Comment by shawna-slh** [comment]
Ideas to provide an example of useful to people without disabilities like many of the other videos do:
- A person breaks their glasses [or the cat chews them up :-] and now the text is blurry, so they need to increase the text size to see it. <- this may be the strongest people can relate to.
- Reading text on mobile phone with ski goggles on - kinda blurry so they increase text size and contrast (maybe reverse) then can read it.
- Reading repair instructions with safety glasses on - kinda blurry so they increase text size and contrast (maybe reverse) then can read it.

Note they'd probably just do browser zoom - best would be to show browser text-only zoom I think.

**Comment by nitedog** [comment]
Script has been revised and this example has been removed.
