### ISSUE TITLE
[Perspectives - Layout]

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#262]
I don't think the link under Learn More > Mobile (tab order) is appropriate for this video.

**Comment by nitedog** [comment]
The [text at this link](https://www.w3.org/WAI/mobile/experiences.html#tab) says:

> "User is unable to navigate content in logical sequence, becomes disoriented." ... "Mobile devices may not have a pointing device so the user may have to navigate elements serially."

Is this not sufficiently related to layout (especially form layout)?

**Comment by susanatx** [comment]
Nothing in the video, nor the links, mentions tab order, keyboard functionality, nor meaningful sequence. If we think it's relevant for mobile why is it not included in the other resources?

I think 1.3.1 re: structure and 3.2.4 are more applicable in this context. (And both of those should be added to the mobile Shared Web Experiences page.)

**Comment by nitedog** [comment]
I agree - valid points. The link will be removed.
