### ISSUE TITLE
[Perspectives - Voice] "software" to "functionality" 

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#264]
In the What is Voice Recognition paragraph I recommend changing "software" to "functionality" or perhaps "assistive technology." I don't think common usage of software translates well to functionality like dictation on which is part of some OSs or Siri on iOS for example.

**Comment by bakkenb** [comment]
+1

**Comment by nitedog** [comment]
Agreed. Will edit accordingly.
