### ISSUE TITLE
[Perspectives - Voice]

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#267]
Suggest adding word in bold:

What needs to happen for this to work?
Keyboard compatibility is the basis for voice recognition **accessibility.**

**Comment by nitedog** [comment]
Can you explain what the intent of this added word is? Or do you mean "voice recognition _for_ accessibility"?

**Comment by susanatx** [comment]
On second look, I don't think the extra word is needed.

**Comment by nitedog** [comment]
Thanks @susanatx
