### ISSUE TITLE
[Script 8: Text Customization] Finishing on the toilet

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#27]
I am _really_ not sure about finishing with happy, smiling, relieved people. Comes a little bit too close to toilet humour for me and I don't know how well that would come across.

Also, why are their three toilet signs? Women, Men, and... ???

**Comment by yatil** [comment]
There are also some cultures that might be _very_ sensitive to even using toilets in such videos.

**Comment by shawna-slh** [comment]
I strongly agree with Eric that it is inappropriate to use this situation in such a video, as it could be offensive to some. Even in some US cultures, it is inappropriate to refer to _it_ at all in mixed company (except only vaguely and when absolutely necessary, e.g., "I'm going to powder my nose before we leave").

**Comment by bakkenb** [comment]
We kicked this issue around a bit too. Adina and I recommended not using the word "toilets" for the signage, but you bring up a good point that the video is still "about" the toilet/restroom. Most people don't want to see or hear about that. One reason why in American TV and movies you usually never hear/see someone say, "I need to go to the restroom/bathroom/toilet," unless it is the very integral part of advancing the story or plot.

When I was little, growing up watching TV. I was always amazed at how nobody had to go to the bathroom. LOL

**Comment by shawna-slh** [comment]
Yup.
LOL!
(I moved from the north -- where we used the term "bathroom" -- to Texas about age 6. Once I wasn't feeling well in school and the teacher asked if I needed to go to the restroom. I assumed it was a room with beds. Imagine my surprise what was there instead. :-)

Bottom line: Gotta do something different for this.

**Comment by nitedog** [comment]
Script has been revised and this example has been removed.
