### ISSUE TITLE
[Perspectives - Keyboard]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#270]
Too many of the intro sections include the phrase "need to" which seems arbitrary and unconnected to where the need comes from. Suggest change first sentence to:

Interactions with web content must be fully keyboard enabled. That is, users must be able to...(etc)

**Comment by chaals** [comment]
As a stylistic thing, two musts in a row seems heavy. How about something like

"Interactions must be fully keyboard enabled, so users who rely on a keyboard interface can… "

**Comment by nitedog** [comment]
OK, there are two aspects in this comment:
1. Too much use of the phrase "need to" across all sections. Agreed and will revise accordingly. However, sometimes the use of the word "must" could be too strong as well. Need to find a balance.
2. "need to" in this particular intro section is too weak. Agreed. And in this case the word "must" can indeed be used, as this is a clear WCAG requirement. AFAIK there is only one occurrence here.
