### ISSUE TITLE
[Perspectives - Keyboard]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#271]
In "What Needs to Happen..." section, I think the suggestion to Mark up tab order is quite risky and can have rather disastrous consequences if done without a lot of knowledge and experience. Suggest something like this instead:  

"Ensure that default and custom tab order is logical and predictable when moving through content and controls."

**Comment by nitedog** [comment]
Agree. Will edit accordingly.

**Comment by sharronrush** [comment]
great, thanks

**Comment by nitedog** [comment]
Changed to "Ensure that the tab order is logical, to allow keyboard navigation around the content and controls".
