### ISSUE TITLE
[Perspectives - Layout]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#272]
The what is clear layout section seems a bit negative and emphasizes too much of what it should _not_ be. Suggestion instead:

Good layout makes a web page clear and compelling, allowing different sections to be easily found and identified. Navigation menus, links, and content sections should be clearly and consistently indicated. Form input fields and submission controls should be labeled and the association with the label should be clear.

**Comment by nitedog** [comment]
Agreed and will edit accordingly.

**Comment by sharronrush** [comment]
Thanks Shadi!
