### ISSUE TITLE
[Perspectives - Customizable]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#273]
First sentence seems strained - and there is that unspecified "need" again.  Alternative suggestion:

Text becomes easier to read for different people depending on font size, style, and color. Technology is well suited to this kind of personalization by allowing users to change the way text is displayed. Many web browsers and mobile devices can support text customization options and render text in a ways that suits the reader, retains all information and function, and reflows text so there is no need for horizontal scrolling to read it.

**Comment by nitedog** [comment]
Will take an editorial pass accordingly

**Comment by shawna-slh** [comment]
It's more than "easier to read", though -- some people cannot read "normal" text at all, and I think that should come through clearly: customizeable text is a user _need_. Current wording with tweak says:

> [Some people] need to be able to change the way text is displayed... in order to read the text.

Probably would be clearer if the " — changing the size, spacing, font, color, and more — " part was put in a separate sentence.
