### ISSUE TITLE
[Perspectives - Captions]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#275]
What "are" video captions (not What is).  The explanatory paragraph is a bit bumpy
Captions are the presentation in text of the audio portion of any media content that includes sound. Captions may include information about who is speaking, sound effects, music, laughter, etc. Captions are synchronized with the visual content. 

Strike the part about "All audio needs to be captioned..." since that is not in fact part of what captions are and is therefore irrelevant to the subject of this section.

**Comment by nitedog** [comment]
Agreed. Will revise accordingly.
