### ISSUE TITLE
[Perspectives - Notifications]

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-showcase-examples#277]
Who depends on this feature?
Include blind users who need clarity for efficient error recovery.

**Comment by nitedog** [comment]
Can you explain this? Maybe a brief scenario of notifications or instructions being more helpful to a blind person than to other audiences?

**Comment by sharronrush** [comment]
I was mostly thinking about the clarity of the notifications, that an error notification message should be specific about which fields are in error.  You know how sometimes an error message just says "Correct the errors below" or doesn't even have a general error message, only the red box around any unfilled or mistakenly filled fields. Don't we want to make the point that the ore specific the error is, the more efficiently it can be found and corrected by a blind user?

**Comment by nitedog** [comment]
Only blind users? "Correct the errors below" is frustrating for most users if the errors are not highlighted. Hmmm. Maybe along the lines of something like this:
- People with partial sight and blindness, who rely on notifications, instructions, and errors messages to understand the context and interactions.
