### ISSUE TITLE
[Perspectives - Customizable]

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-showcase-examples#284]
is "... and some mobile applications to do use the text settings" actually referring to sites/apps that lock out zoom and user preferences?

So, should [... and some mobile applications to do use the text settings.] really be something like [... and some mobile applications to do not allow use of the text settings.]?

**Comment by nitedog** [comment]
Bah, not sure what happened there! It should be:
- Some web browser plug-ins do not provide the text settings users need, and some mobile applications do not use existing text settings.

**Comment by AndrewArch** [comment]
ok - fine :)
