### ISSUE TITLE
[Perspectives - Customizable]

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-showcase-examples#285]
"Content is more ready for translation, to adapt to words and sentences of different lengths" read very oddly to me, but haven't got a suggestion for better expression right now.

**Comment by nitedog** [comment]
How about:
- Content is more adaptable to words and sentences of different lengths, when it is translated

**Comment by shawna-slh** [comment]
How about:

> Content is more adaptable to translation into words and sentences of different lengths.

or:

> Content is more adaptable for translation into words and sentences of different lengths.

or:

> Content is more adaptable when translated, since words and sentences are different lengths in different languages.

**Comment by AndrewArch** [comment]
Must admit I'm still not sure what the point being made is, even with the suggested alternatives :(

**Comment by nitedog** [comment]
In German, for example, you can have words like [donaudampfschifffahrtsgesellschaftskapitaenswitwe](http://www.bbc.com/news/blogs-magazine-monitor-22765498). These usually break all designs if they can't adapt for words of different lengths.
