### ISSUE TITLE
[Script 9: Simple Language] Example form

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#29]
Sequence 3 visuals suggest a form with complicated langage. This might be quite hard to communicate as forms are not usually replete with byzantine language.

(See what I did there :))

**Comment by nitedog** [comment]
I'm envious that you have understandable tax forms! ;)

But true, maybe online shops are less often cryptic. Or are they?

**Comment by nitedog** [comment]
From Susan:

>  A complicated form seems more applicable to consistent layout than language. Maybe he should pull up a recipe that's full of jargon and unexplained acronyms. This would match the narration for that scene and overall subject better.

**Comment by nitedog** [comment]
Script has been revised and this example has been removed.
