### ISSUE TITLE
[Speech][low-med] What needs to happen... accurate perspective? :)

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#290]
I know we want to keep the What needs to happen... sections basic and short; however, I wonder if for this one, what's here is giving a very false sense of all that is required? Or maybe it's OK since we have lots under "Learn More"?

**Comment by nitedog** [comment]
It is rather short. What else do you feel is essential to tell for someone just starting (and keeping in mind the links below, as you point out)?
