### ISSUE TITLE
[perspectives - keyboard] shortcuts have to be obvious

### ISSUE THREAD

**Issue by chaals** [w3c/wai-showcase-examples#291]
This is hard, because there isn't so much a best practice as various least-worst ones. But it is really important that shortcuts are discoverable, and that they don't override defaults in the user's system.

Which isn't that easy to achieve in practice :(

**Comment by nitedog** [comment]
@chaals - I agree. But did you mean discoverable as in "programatically determined" (eg using label and ARIA attributes), or visually identifiable (eg keyboard focus and CSS presentation), or both?

**Comment by nitedog** [comment]
The word "shortcuts" has been replaced by "keystrokes", which resolves this issue.
