### ISSUE TITLE
[Keyboard] blocks of contents

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#299]
[minor - for editors discretion]

Current wording:

> Provide a way for users to jump between groups of related controls.

"related controls" doesn't seem right.

WCAG wording:

> 2.4.1 Bypass Blocks - A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.

Maybe more like:

> Provide a way for users to go directly to blocks of information, such as navigation and main content.

**Comment by nitedog** [comment]
Good suggestion. But "go directly" reminds me too much of access keys. How about "jump between blocks of information/content"? My concern is that "blocks" is a little jargony.
