### ISSUE TITLE
[scenarios] reference targets

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#3]
From Kevin White @iadawn : 

Do we want to point to something other than w3.org/WAI? The home page may not be the best place for the target audiences.

**Comment by yatil** [comment]
That also crossed my mind. I guess we should have short links at the end of the videos that link to the individual showcase page and have more detailed links from there.

**Comment by nitedog** [comment]
The Getting Started Tips are also likely candidates, but that will show when we have the content more worked out.

**Comment by nitedog** [comment]
Duplicate of #8
