### ISSUE TITLE
[Captions] transcribed?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#307]
> Content can be more easily transcribed using the captions, which also improves indexing for search engines.

This doesn't make sense. Captions are created with transcribed info.

Also, I think some search engines now directly access caption files...

**Comment by nitedog** [comment]
We previously had a concern about this search engine assumption - it is either not very common or not commonly known.
How about "Content in text form, such as caption files and transcripts, can be better indexed by search engines"?

**Comment by shawna-slh** [comment]
+1
