### ISSUE TITLE
[Script 9: Simple Language] Cognitive disability is not that simple

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#31]
I wonder if there is a simpler phrase for 'cognitive disability' that is acceptable. Tricky (hence the lack of suggestions) as it sums up more than just learning disabilities. Maybe 'intellectual disabilities'.

**Comment by nitedog** [comment]
The text says "some forms of cognitive disabilities" - maybe say "some forms of cognitive and intellectual disabilities"? Yes, terminology in this space is very tricky.

**Comment by nitedog** [comment]
The ending now says "Websites that use clear and understandable language provide access to people with learning and cognitive disabilities and they are are easier to use by everyone." It doesn't say "all people with learning and cognitive disabilities". Note that also the scope has been expanded to include structure, like headings and lists etc. There will be more opportunity for explanation on the landing page for these videos.

**Comment by James-Green** [comment]
What about "cognitive challenges"?

**Comment by nitedog** [comment]
Would it be weird to switch from "people with [x] disabilities" to "people with [x] challenges" when we are talking about cognitive? I think this would require quite some revision of all videos.

Also, not sure it helps address @iadawn 's concern - I understand he is concerned about combining all the different aspects in just one term "cognitive disabilities". I hope that this is addressed by using the broader phrase "learning and cognitive disabilities" to help signal the broad spectrum of coverage. It is also the term used by WCAG (eg. http://www.w3.org/WAI/PF/cognitive-a11y-tf/).

**Comment by nitedog** [comment]
I think that has been addressed. @iadawn and @James-Green please reopen if you feel this needs further addressing.
