### ISSUE TITLE
[Perspectives - Customizable] "scroll horizontally"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#310]
"scroll horizontally" is for left-to-right and right-to-left languages.

ACTION: Shawn check with I18N folks on this issue...

**Comment by nitedog** [comment]
@slhenry any news on this issue?

**Comment by shawna-slh** [comment]
https://lists.w3.org/Archives/Public/w3c-wai-eo/2016JulSep/0014.html

**Comment by yatil** [comment]
We got a response from @r12a a while back: https://lists.w3.org/Archives/Public/w3c-wai-eo/2016JulSep/0030.html

**Comment by yatil** [comment]
@slhenry @nitedog Anyone wants to address this?

**Comment by yatil** [comment]
This issue was moved to w3c/wai-website#821
