### ISSUE TITLE
[Perspectives - Overview et al] Resize thumbnail images. 

### ISSUE THREAD

**Issue by yatil** [w3c/wai-showcase-examples#314]
Images have the full video resolution and are then shrunk in the browser. This means users have to download more data which makes our pages sluggish. I think resizing it to the double size of the display should be enough to make sure that they look good on retina screens.

**Comment by bakkenb** [comment]
I agree. 

How much of a reduction of the original is it if you go down to "double the size of the display?"

**Comment by yatil** [comment]
Brent: Currently the images are 3904K, resized and optimized it is about 196K. Savings of 95%.

More info at #315.
