### ISSUE TITLE
[Script 10: Keyboard Compatability] Opening sequences don't make sense

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#32]
Why would not being able to open a car window stop one using a car? I am afraid this make no sense at all.

Also, in the second sequence all laptops now come with some form of mouse replacement. It is sometimes frustrating to use, but not to the extent of not using.

**Comment by yatil** [comment]
> Imagine if you couldn’t use your car because you couldn’t open your window.

That is indeed hard to imagine. A working analogy could be stick shifting vs. automatic transmission, but I fail to see how that helps with the keyboard navigation compatibility.

**Comment by bakkenb** [comment]
We discussed the idea of the issue being a navigation system that is not working. Get in the car and the nav system says that it is not functioning/error. So the person won't use the car. Production worried that it would be a bit difficult to get footage of that to look good.

Could we explore more ideas with a car scenario?

**Comment by shawna-slh** [comment]
I had also noted:
- opening doesn't make sense - nor the closing with the automatic
- laptops have trackpads or some mousey thing

**Comment by nitedog** [comment]
From Susan:

> Change scene one to match the fifth. Having a window that doesn't open won't prevent you from driving a car nor is it related to the type of transmission. Maybe in the first scene for some reason they can't operate the shift stick - they don't know how, it's stuck, or they have some sort of physical limitation.

**Comment by nitedog** [comment]
From Judy:

> The initial scenario doesn't seem credible and could be replaced

**Comment by nitedog** [comment]
Script has been revised and this example has been removed.
