### ISSUE TITLE
[Script 10: Keyboard Compatability] Uncertain it conveys the point well

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#34]
I think this script does not respond that well to the requirements at the top of the page. It doesn't really make sense and doesn't convey the problems that can come with lack of keyboard accessibility. 

Sorry, no immediate bright ideas.

I think it needs a more believable analogy and needs to show interactions that limit a keyboard only user. Inability to submit a form, unable to close a modal window, dunno.

**Comment by nitedog** [comment]
From James:

> I don't get the window analogy at all. Given the ending with an automatic, wouldn't it make more sense to use a manual transmission as the analogy? Manual transmissions only have one way to drive them, can't use the stick, you can't drive. If the car at the end was an automatic that also had a manual mode, that would be a lot better analogy.

**Comment by nitedog** [comment]
General discomfort with this analogy from the working group: https://www.w3.org/2016/02/12-eo-minutes.html#item04

**Comment by nitedog** [comment]
Script has been revised and this example has been replaced with broken mouse, in agreement with the working group: https://www.w3.org/2016/02/26-eo-minutes.html#item03
