### ISSUE TITLE
[Script 4: Text to Speech] Gender stereotypes

### ISSUE THREAD

**Issue by yatil** [w3c/wai-showcase-examples#35]
> Cut to a mum listening to a magazine article as she does the washing.

I hope she is at least listening to a DIY car repairing magazine or washes her sky diving gear :-)

**Comment by iadawn** [comment]
+1 to avoiding sterotypes :)

**Comment by bakkenb** [comment]
Very good point. Good catch.

**Comment by shawna-slh** [comment]
:+1:

I noticed the same issue in at least one other place, but may not have noted it, so it would be good to go through each script to check for it.

Also a related issue is an older person having trouble with the computer -- especially when a younger person comes to help -- even if the younger person is also perplexed. Possibly it could work if the _older_ person finds the fix and that is clear. This is in Script 6 and one other I think.

**Comment by nitedog** [comment]
From Susan:

>  Also, perhaps we can switch the gender of the actors to a woman sitting in an office and a man doing the washing? It might seem a minor thing to some but that kind of representation goes far for others.

From Judy:

>  Does it need to be a mum who's doing the washing?

**Comment by nitedog** [comment]
Removed.
