### ISSUE TITLE
[Script 7: Large Click Areas] Click vs. tap

### ISSUE THREAD

**Issue by yatil** [w3c/wai-showcase-examples#36]
The narration says click areas when the video shows tapping on a tablet. It should at least say tap or click area or bypass that problem by saying “large targets”.

**Comment by nitedog** [comment]
do we say "large click and tap areas" or "large activation" areas, which is simpler but quite jargony? Or just avoid altogether and say "large areas"? But areas of what? Ideas?

**Comment by yatil** [comment]
<brainstormmode> “large areas to tap or click” might work… or “large buttons to press” depending on the situation…

**Comment by nitedog** [comment]
Script has been changed accordingly.
