### ISSUE TITLE
[Script 7: Large Click Areas] Laptop in bus

### ISSUE THREAD

**Issue by yatil** [w3c/wai-showcase-examples#37]
> Pull out from the person – they’re not sat on a chair at home, they a passenger on a bus.     
> 
> Move to the person next to them who is working on a laptop and has a tremor meaning the cursor moves a lot. The person with the tremor manages to click on what they want thanks to large click area.

How do you make sure that people understand that the person is having the tremor and that it is not just complicated to click on stuff because the bus is moving? I think I see the point that you’re trying to make (involuntary movements), but I don’t think putting the people into a bus helps a lot. As there need to be a cut from the needle threading to the website using, why not show the tablet person with a mobile phone while walking (creates enough bounce that it is hard to target tiny things), then sitting down in a café or where on another table the person with the tremor uses the computer.

**Comment by bakkenb** [comment]
+1

**Comment by nitedog** [comment]
Script has been changed accordingly.
