### ISSUE TITLE
[Script 5: Layout and Design] harmful hyperbole

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#39]
I had a very strong negative reaction to this:

<blockquote>There are few things in life more frustrating than a poor layout</blockquote>

-- how about inaccessible buildings, health insurance not covering recommended medical treatments, -- you get the point.

In [Script 8: Text Customization] I noted a similar thing in:

<blockquote>In every area of life text plays a vital role</blockquote>

-- naw, how about love, how about all the people who cannot process text, etc.

Please check through all of the scripts for this kind of thing.

**Comment by shawna-slh** [comment]
found another one:
- 6: "Clear instructions... make everything in life much simpler"

-- doesn't make it easier for me to walk, etc...

**Comment by nitedog** [comment]
Continued in #14
