### ISSUE TITLE
[Script 1: Video Captions] Unsure about hearing aid

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#4]
I appreciate that there needs to be some way to indicate that the observer in sequence 4 has a hearing disability, but if they have a hearing aid why would they need captions? Unless the hearing aid doesn't work.

An extreme analogy might be showing someone wearing glasses but indicating they need to use a white cane. Maybe a bit too much of an extreme analogy.

**Comment by yatil** [comment]
I agree. Maybe just briefly show them signing with someone. Brainstorm:
- Watching a movie, the bottom part (where the captions are) is hidden. There is no sound in the scene.
- Someone walks across the room (possibly in the back, viewers don’t need to know who this is), the actor signs briefly, then looks at the tablet again.
- Now we see that the movie is captioned.

**Comment by nitedog** [comment]
Some people using hearing aids also use captions, but I agree that this may not be apparent to the target audience of the video and potentially confusing. Will revise this.

**Comment by nitedog** [comment]
Changed to sign-language, similar to what @yatil suggest.

**Comment by nitedog** [comment]
This change to sign-language adds a lot of complexity.

The point is to show someone who requires (as opposed to prefers) captions. There are many people who use hearing aids and closed captions - the question is if this will be too confusing for some viewers? Note: the video links to a page with a blurb with further explanations and links.

**Comment by shawna-slh** [comment]
Agree there are people who use hearing aids and closed captions, and I think that's fine.

**Comment by nitedog** [comment]
Working group resolution to show someone using hearing aid and closed captioning: https://www.w3.org/2016/02/19-eo-minutes.html#resolution01
