### ISSUE TITLE
main point not come through

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#47]
I wonder if the main point of each video doesn't come through clearly? When reviewing scripts, we have it in mind because we saw the heading. But I don't see it clearly in the narration or visuals for some of the scripts.

The videos might need visual text at the beginning and ending to make it clear. (and the text would probably be a little different from the current headings)

**Comment by nitedog** [comment]
@slhenry - scripts have been revised to address this issue. Do you still have this concern?

**Comment by shawna-slh** [comment]
It looks like most (or all) scripts have "[VIDEO TITLE]" as the first Visual. It would be good to put the actual text there now, and then ask EOWG to review it. Per above, for some of the videos, that text might not be exactly the "handle"/working-title that we've been using.

Did we/you further discuss having the text at the end - and decide not to do that? It seems it might be simple to repeat that text with the web address. I don;t fee strongly about that.

**Comment by shawna-slh** [comment]
A related point: I noticed Sharron included "XYZ is part of web accessibility" in a [survey](https://www.w3.org/2002/09/wbs/35532/showcase3/results) -- and it got me thinking from a higher level... what about people who land on a video (from search or a link given them or whatever) without context... hum... probably we should have the phrase "web accessibility" at least visually (and in audio description) at the beginning and/or the ending...

**Comment by nitedog** [comment]
These issues are being addressed by #109 (catchy phrase) and #108 (start/end screens).
