### ISSUE TITLE
[Script 2: Color Contrast] Road signs?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#5]
I wasn't sure what type of roadsigns a pedestrian might need to see and what sort of signs might have poor contrast.

**Comment by nitedog** [comment]
Related comment from James:

> This is promising, but I'd want to see the street signs they intend to use. To me, believability is key - we better find signs with low contrast that would actually be a problem for people. If it looks like a set up to illustrate our point, we lose credibility in my opinion.

**Comment by nitedog** [comment]
The idea is to show "what if roadsigns were not clear" rather than claiming that there are unclear roadsigns - if something what we take for granted every day became inaccessible to us. But agree that this could be confusing and will revisit with the Task Force.

**Comment by nitedog** [comment]
Clarified the text some more. This should become apparent with the visuals. There is not claim that roadsigns have poor contrast - it is to show the importance of good contrast.

**Comment by AndrewArch** [comment]
not sure if it helps, but [A world made for disabilities](https://www.youtube.com/watch?v=RsuKxY_9f_8) was a "what if" video

**Comment by nitedog** [comment]
Working group discussion with strong preference to change the example to something that is:
1. More realistic and encounterable, like a menu with bad contrast, to make it closer to the viewer;
2. Ideally something more substantial (and existential) than a menu (maybe some instructions?).

Suggestions for such example situations are welcome!

**Comment by nitedog** [comment]
After lots of discussion, we could not find a better example. We made several edits to the wording and clarification to the visuals. We really think that this will work out nicely once implemented visually.
