### ISSUE TITLE
[8: Text Customization] design and coding together

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#53]
seq 7: "Good design allows anyone to resize or recolor text without loss of formatting function or clarity."
seq 8: "Proper coding makes the content fully customisable."

Especially reading the transcript, a person could think that good design does X and proper coding does Y -- but it's really both good design and good coding together.

I also put related pull requests thinking about the lines individually -- but they need to be thought of together...

**Comment by nitedog** [comment]
Script has been revised accordingly.
