### ISSUE TITLE
[8: Text Customization] visual disabilities -> low vision?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#54]
<blockquote>Meaning that people with visual disabilities and dyslexia can use them</blockquote>

(also related to https://github.com/w3c/wai-showcase-examples/pull/48 )

I think many people in the one of the target audiences for these videos associate "visual disabilities" with blindness only, not low vision. I wonder if "low vision" is a better term to use in this context?

/me wants to check out understandably of "low vision" in other regions, e.g., where "partially sighted" is the more formal term...

**Comment by nitedog** [comment]
Script has been revised accordingly.
