### ISSUE TITLE
[8: Text Customization] cognitive color and font face

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#55]
<blockquote>The person who saw the text jumbled replaces the sign with one with a different colour scheme – they read it clearly</blockquote>

In a <a href="http://www.tader.info/survey1304.html">survey on text customization<a/>, people with cognitive disabilities (and _not_ visual disabilities) rated as most important: color and font face -- so if we keep something like this, it would be good to also change the font from a "fancy" font to a simple sans serif font.

**Comment by iadawn** [comment]
One concern I would have with this is that it could easily be perceived as saying that accessibiity means you have to make design boring.

**Comment by nitedog** [comment]
Are there references in WCAG or UAAG regarding the suggested choice of colors and font face? Otherwise we would imply something that is not (yet) supported by the guidelines.

**Comment by nitedog** [comment]
Script has been revised and this example has been removed.
