### ISSUE TITLE
[3: Voice] evolved speech

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#57]
<blockquote>If you could only communicate with your family by writing, imagine how long everything would take. That’s why we evolved speech... </blockquote>

Seems like that's saying that in human evolution writing came first and then speech, which I;m pretty sure was not the case. :)

**Comment by nitedog** [comment]
From Judy:

> This is confusion because that's not why we evolved speech; speech evolved eons before writing evolved. Could just note that speech can be a far more efficient mode of communication.

**Comment by nitedog** [comment]
Removed.
