### ISSUE TITLE
[3: Voice] future, nobody

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#58]
"It's the way of the future" -- not sure if we can say that.

"Nobody knows how far this technology has come better than people with physical disabilities - many have been relying on it for years". Not really true, especially with "Nobody". I'm sure there are many people with physical disabilities who don't know much about it. And there are experts in the field w/o disabilities who do know all about it.

**Comment by nitedog** [comment]
From Judy:

> Many people who are blind would probably argue with you on that point. Suggest rephrasing.

**Comment by nitedog** [comment]
Removed.
