### ISSUE TITLE
[2: Contrast] color blind minor

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#65]
The main need for higher contrast is by people with low contrast sensitivity. People with different visual conditions have low contrast sensitivity, and contrast sensitivity decreases with age.

I think that in general, people who are colorblind do _not_ have lower contrast sensitivity. If colors are used that they cannot discern, then having sufficient contrast will enable them to discern.

So I think the presentation isn't right on a few points.

I edited Sequence 5 as: "And this can be especially problematic for people with low contrast sensitivity, which is common as we age - and we're all aging! To those people, this, can look like this!
Good contrast can also help the approximately 1 in 12 males who are colorblind – that’s a lot of people." ... then I saw aging in the next Sequence.

I do think the focus and specific words need to be changed.

See also related issues...

**Comment by nitedog** [comment]
Addressed.
