### ISSUE TITLE
[2: Contrast] won't help

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#66]
<blockquote>Older person walks into the room and rubs their eyes – contrast returns to normal</blockquote>

IMPORTANT: No! this implies a person just rubs their eyes and then magically their contrast sensitivity returns.:( Age-related contrast sensitivity loss is permanent and you cannot get it back, afaik.

<blockquote>has to walk right up to the signs to try to figure them out</blockquote>

I'm pretty sure that getting closer would not help.

<blockquote>The person using the app looks at a poorly contrasted button that becomes clear as they look at it.</blockquote>

Meaning the contrast gets stronger?

**Comment by nitedog** [comment]
Removed.
