### ISSUE TITLE
[Script 2: Color Contrast] Jumping around

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#7]
The visuals in this seem to jump around a lot:
- First we are in the street with a road sign (1-2)
- Then street with an app (3-4)
- Then person on a sofa looking at tablet (5)

And wasn't sure about older person coming in rubbing their eyes.

I think the text also jumps around a bit, particularly in sequence 6

**Comment by nitedog** [comment]
Revised scenes and sequences.
