### ISSUE TITLE
[General] What to link to

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#8]
Is w3.org/WAI the best thing to link to for the target audience? Maybe Getting Started?

**Comment by yatil** [comment]
I would really like to see dedicated pages for the videos, that give very brief but specific links to more content. I think just linking to /WAI is not particularly useful.

I see the challenge making links specific (w3.org/WAI/videos/captions) but then they might be quite long. A custom URL could help. (a11y.video is still available :-D).

**Comment by bakkenb** [comment]
I agree with both Eric and Kevin. I think that what we link to needs to be specific yet simple/beginner type information. Most who will be attracted by the content of the videos and think, "where do I start" will be newbees, so we don't want the links to go to something that will overwhelm them immediately.

**Comment by shawna-slh** [comment]
My understanding was that the videos were just one part, and for each there would be a corresponding web page that would explain more and link to relevant resources in WCAG and elsewhere (probably only on the WAI website). I think this is a **must** (even if the videos get done in Q1 and the web pages don't get done until Q2).

Possibility for simplicity we have one overview/landing page for all _(such as /WAI/examples or /WAI/eg or /WAI/egg :-)_, that has links to the sub-pages for the specific issues.

**Comment by nitedog** [comment]
Yes, this is the plan. The question is what this URL would be. I like w3.org/WAI/examples but other (shorter?) ideas welcome too. Needs to be persistent, so probably best to stick with a W3C page?

**Comment by shawna-slh** [comment]
Above I went from /WAI/examples ...to... /WAI/eg (as in e.g. short for "examples") ...to... /WAI/egg

/WAI/egg  is short and memorable :-) like finding the golden egg :-)

**Comment by nitedog** [comment]
I don't like "eg" or "egg" but happy to go with the suggestion of the outreach coordinator.

**Comment by shawna-slh** [comment]
I think we need to figure out the name of this resource / title of the page before deciding on a URI. afaik, "showcase examples" was a working title only, and EOWG has not decided what to call these. It would be good to figure that out and have at least a rough draft page before finalizing the URI.

/me hopes EOWG folks can find patience for another naming task :-/

**Comment by bakkenb** [comment]
Based on the teleconference discussion around the title of the resources, I am listing out some of the key points that came to the surface.
- Specific enough that the title could not be used for other resources
- Words most people liked: Impact, benefit
- Title should include an action verb - invoking call to action, invitation, participate
- Catchy, not boring

Some ideas I would like to bounce off of others (edited based on @iadawn comment below):
- Showcasing the Impact and Benefits of Web Accessibility 
- Showcasing the Benefits and Impact of Web Accessibility
- See the Benefits, Make an Impact: Web Accessibility
- See Benefits, Make Impact: Web Accessibility
- Benefits and Impact: The Accessibility Showcase
- Accessibility Expose
- Tune in to Web Accessibility
- Tune In and Take Off, with Web Accessibility!

**Comment by iadawn** [comment]
I noted in the call a preference for placing 'benefits' before 'impact'. I think 'benefits' is a stronger, more positive, less ambiguous word to lead with. If those terms were used, that would be my preference.

**Comment by shawna-slh** [comment]
I skimmed the [4 March minutes](https://www.w3.org/2016/03/04-eo-minutes.html#item04). One of the big points in the videos is how accessibility often benefits _everyone_ in various situations. I think we want that to come through in the title, e.g.,
- **Web Accessibility Impacts and Benefits Everyone**
- Web Accessibility Impact and Benefits for Everyone
- Web Accessibility Experiences: Learn about impacts and benefits for everyone
- Web Accessibility Illustrations &mdash; It impacts people with disabilities and benefits everyone
- Web Accessibility Perspectives for People with and without Disabilities
- Web Accessibility in Action: Impact for People with Disabilities and Benefits for Everyone
- Web Accessibility for People with and without Disabilities
- Web Accessibility is Essential for People with Disabilities and Beneficial for Everyone
- Web Accessibility: Essential for People with Disabilities & Beneficial for Everyone

**Comment by bakkenb** [comment]
I like a combination of two of your titles @slhenry.
- Web Accessibility Perspectives: Learn about benefits and impacts for everyone
  <br>or
- Web Accessibility Perspectives: Explore the benefits and impacts for everyone

**Comment by nitedog** [comment]
Proposed final URL: http://www.w3.org/WAI/perspectives - short: w3.org/WAI/perspectives

**Comment by yatil** [comment]
Just to clarify: It will be the same URL in every video?

**Comment by nitedog** [comment]
Yes - all videos will be on the same page, currently drafted here: http://w3c.github.io/wai-showcase-examples/Overview

**Comment by bakkenb** [comment]
Just to add it to this issue thread... The final approved resource name is "Web Accessibility Perspectives: Explore the Impact and Benefits for Everyone"

Therefore "w3.org/WAI/perspectives" seems like a great URL.
