### ISSUE TITLE
[Script 3: Voice Recognition] Evolved speech

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#9]
It may be better to say something like:

> Speech makes this much easier

To be a bit flippant, I don't know that speech was evolved to confirm kids don't know what they want to eat ;)

**Comment by yatil** [comment]
I agree that this is a bit too constructed for my taste. Of course only writing would be terrible, but there are a lot of other things that you can do to communicate, for example to shrug. What about showing two people communicating (about slightly less trivial things) through a train window, a glass wall at an airport or something like that.

**Comment by nitedog** [comment]
From Susan:

>  It's confusing because it implies the purpose of having speech is saving time but the need for voice recognition is not for the benefit of time saved. I would have to think on it a bit to come up with a suggestion to replace it but I strongly feel this is not a good lead-in concept.

From Judy:

>  This is confusion because that's not why we evolved speech; speech evolved eons before writing evolved. Could just note that speech can be a far more efficient mode of communication.

**Comment by nitedog** [comment]
Removed.
