### ISSUE TITLE
[2: Color Contrast] (minor) Road signs

### ISSUE THREAD

**Issue by yatil** [w3c/wai-showcase-examples#98]
I’m still not sure about the altered road signs. At least I think that Sequence 1 (walking through the unaltered signs) might be redundant – I think we can assume that people know how signs are supposed to look. But I am happy to be surprised by the result of the filming. 

Related to: #5

**Comment by nitedog** [comment]
I don't understand the redundancy aspect. The roadsigns are normal with clear contrast. We take that for granted each day. Then it is turned - what if you didn't have clear contrast? ... this is how some people encounter the world, especially with bad design. Hope this clarifies?

**Comment by yatil** [comment]
I think it is clear, but I don’t know if it is 100% necessary. This might be decided after shooting when cutting the showcases. I really don’t feel strongly at all (thus closing this as resolved).

**Comment by nitedog** [comment]
From George:

> Some other possible areas besides road signs could be schedules for public transportation such as bus and train schedules. Especially the giant train schedule boards you see in train stations or the led based bus signage on the buses themselves. Just a thought:)

**Comment by nitedog** [comment]
@yatil would George's suggestion also address your concern? That is, use digital signage instead of road signs to visualize "what if your world looked different"? I'm still missing your concern - what is not 100% necessary?

**Comment by yatil** [comment]
I have no concern. I think that street signs are deliberately designed to have high contrasts and are easy to read. I wonder(ed) if the opening scene would be more impactful if the signs without contrast were there immediately. Otherwise I think the street-sign approach is also fine with me and we don’t need to search for alternatives.

**Comment by nitedog** [comment]
Will be (logistically) difficult to get overhead signs. The video production company is certain that they can achieve the necessary effect with road signs.
